// Package job provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package job

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/cybroslabs/hes-2-apis/openapi/openhes/attribute"
	externalRef0 "github.com/cybroslabs/hes-2-apis/openapi/openhes/driver/driverdata"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ActionTypeSchema.
const (
	FWUPDATE             ActionTypeSchema = "FW_UPDATE"
	GETCLOCK             ActionTypeSchema = "GET_CLOCK"
	GETDISCONNECTORSTATE ActionTypeSchema = "GET_DISCONNECTOR_STATE"
	GETEVENTS            ActionTypeSchema = "GET_EVENTS"
	GETIRREGULARPROFILE  ActionTypeSchema = "GET_IRREGULAR_PROFILE"
	GETLIMITER           ActionTypeSchema = "GET_LIMITER"
	GETPERIODICALPROFILE ActionTypeSchema = "GET_PERIODICAL_PROFILE"
	GETREGISTER          ActionTypeSchema = "GET_REGISTER"
	GETRELAYSTATE        ActionTypeSchema = "GET_RELAY_STATE"
	GETTOU               ActionTypeSchema = "GET_TOU"
	RESETBILLINGPERIOD   ActionTypeSchema = "RESET_BILLING_PERIOD"
	SETDISCONNECTORSTATE ActionTypeSchema = "SET_DISCONNECTOR_STATE"
	SETLIMITER           ActionTypeSchema = "SET_LIMITER"
	SETRELAYSTATE        ActionTypeSchema = "SET_RELAY_STATE"
	SETTOU               ActionTypeSchema = "SET_TOU"
	SYNCCLOCK            ActionTypeSchema = "SYNC_CLOCK"
)

// Defines values for BulkStatusEnumSchema.
const (
	BulkStatusEnumSchemaCANCELLED BulkStatusEnumSchema = 3
	BulkStatusEnumSchemaCOMPLETED BulkStatusEnumSchema = 2
	BulkStatusEnumSchemaEXPIRED   BulkStatusEnumSchema = 4
	BulkStatusEnumSchemaQUEUED    BulkStatusEnumSchema = 0
	BulkStatusEnumSchemaRUNNING   BulkStatusEnumSchema = 1
)

// Defines values for JobActionResultSchemaCode.
const (
	JobActionResultSchemaCodeERROR        JobActionResultSchemaCode = "ERROR"
	JobActionResultSchemaCodeNOTPROCESSED JobActionResultSchemaCode = "NOT_PROCESSED"
	JobActionResultSchemaCodeOK           JobActionResultSchemaCode = "OK"
	JobActionResultSchemaCodeUNSUPPORTED  JobActionResultSchemaCode = "UNSUPPORTED"
)

// Defines values for JobErrorCodeSchema.
const (
	JobErrorCodeSchemaERROR JobErrorCodeSchema = "ERROR"
	JobErrorCodeSchemaFATAL JobErrorCodeSchema = "FATAL"
	JobErrorCodeSchemaNONE  JobErrorCodeSchema = "NONE"
)

// Defines values for JobStatusCodeEnumSchema.
const (
	JobStatusCodeEnumSchemaCANCELLED JobStatusCodeEnumSchema = 3
	JobStatusCodeEnumSchemaCOMPLETED JobStatusCodeEnumSchema = 2
	JobStatusCodeEnumSchemaEXPIRED   JobStatusCodeEnumSchema = 4
	JobStatusCodeEnumSchemaQUEUED    JobStatusCodeEnumSchema = 0
	JobStatusCodeEnumSchemaRUNNING   JobStatusCodeEnumSchema = 1
)

// ActionID The ID of the action.
type ActionID = openapi_types.UUID

// ActionTypeSchema The type of action.
//   - `GET_REGISTER` - The action is to get billing value, for example instantaneous values.
//   - `GET_PERIODICAL_PROFILE` - The action is to get periodical profile, for example load-profile.
//   - `GET_IRREGULAR_PROFILE` - The action is to get non-periodical profile, for example daily profile or monthly billing registers.
//   - `GET_EVENTS` - The action is to get event log.
//   - `GET_CLOCK` - The action is to get the clock.
//   - `SYNC_CLOCK` - The action is to synchronize the clock. The action synchronizes the clock in the device, it can forcefully set it if force attribute is set.
//   - `GET_RELAY_STATE` - The action is to get the relay state.
//   - `SET_RELAY_STATE` - The action is to set the relay state.
//   - `GET_DISCONNECTOR_STATE` - The action is to get the disconnector state.
//   - `SET_DISCONNECTOR_STATE` - The action is to set the disconnector state.
//   - `GET_TOU` - The action is to get the time-of-use table.
//   - `SET_TOU` - The action is to set the time-of-use table.
//   - `GET_LIMITER` - The action is to get the limiter settings.
//   - `SET_LIMITER` - The action is to set the limiter settings.
//   - `RESET_BILLING_PERIOD` - The action is to reset billing period.
//   - `FW_UPDATE` - The action is to start firmware update.
type ActionTypeSchema string

// AttributesSchema Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
type AttributesSchema = attribute.Attributes

// BulkID The ID of the bulk job. The ID must be unique across the OpenHES components.
type BulkID = openapi_types.UUID

// BulkSpecSchema Schema that holds the one or more jobs for single driver type.
type BulkSpecSchema struct {
	// Actions List of actions to be queued. The empty array is not valid, at least one action must be present. The actions are processed in the order they are defined in the list.
	Actions JobActionListSchema `json:"actions"`

	// CorrelationID The correlation ID of the bulk. The correlation ID is used to group the bulks.
	CorrelationID *string `json:"correlationID"`

	// Devices List of devices to be queued.
	Devices JobDeviceListSchema `json:"devices"`

	// DriverType The driver type related to the job. The type must be one of the supported driver types.
	DriverType string `json:"driverType"`

	// Id The ID of the bulk job. The ID must be unique across the OpenHES components.
	Id BulkID `json:"id"`

	// Settings Schema that holds the settings of the job.
	Settings *JobSettingsSchema `json:"settings,omitempty"`

	// WebhookURL The URL of the webhook to send the notification when any job in the bulk is done.
	WebhookURL *string `json:"webhookURL"`
}

// BulkStatusEnumSchema The status of the bulk.
type BulkStatusEnumSchema int

// BulkStatusSchema Schema that holds the status of the bulk of jobs.
type BulkStatusSchema struct {
	// FinishedAt The time when the bulk has been marked as completed.
	FinishedAt *time.Time `json:"finishedAt"`

	// StartedAt The time when the bulk has been queued for processing.
	StartedAt *time.Time `json:"startedAt"`

	// Status The status of the bulk.
	Status BulkStatusEnumSchema `json:"status"`
}

// ConnectionTypePhoneSchema Schema that holds the phone connection info.
type ConnectionTypePhoneSchema struct {
	// Number The phone number of the device.
	Number string `json:"number"`
}

// ConnectionTypeSchema defines model for ConnectionTypeSchema.
type ConnectionTypeSchema struct {
	union json.RawMessage
}

// ConnectionTypeSerialSchema Schema that holds the phone connection info.
type ConnectionTypeSerialSchema struct {
	// Number The phone number of the device.
	Number string `json:"number"`
}

// ConnectionTypeTcpSchema Schema that holds the TCP connection info.
type ConnectionTypeTcpSchema struct {
	// Host The IP address or hostname of the device.
	Host string `json:"host"`

	// Port The port number of the device.
	Port int `json:"port"`
}

// JobActionCommonSchema Common fields shared for all actions.
type JobActionCommonSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id ActionID `json:"id"`
}

// JobActionFwUpdateSchema defines model for JobActionFwUpdateSchema.
type JobActionFwUpdateSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id           ActionID `json:"id"`
	TypeFwUpdate int      `json:"type_fw_update"`
}

// JobActionGetClockSchema defines model for JobActionGetClockSchema.
type JobActionGetClockSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id           ActionID `json:"id"`
	TypeGetClock int      `json:"type_get_clock"`
}

// JobActionGetDisconnectorStateSchema defines model for JobActionGetDisconnectorStateSchema.
type JobActionGetDisconnectorStateSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                       ActionID `json:"id"`
	TypeGetDisconnectorState int      `json:"type_get_disconnector_state"`
}

// JobActionGetEventsSchema defines model for JobActionGetEventsSchema.
type JobActionGetEventsSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id            ActionID `json:"id"`
	TypeGetEvents int      `json:"type_get_events"`
}

// JobActionGetIrregularProfileSchema defines model for JobActionGetIrregularProfileSchema.
type JobActionGetIrregularProfileSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                      ActionID `json:"id"`
	TypeGetIrregularProfile int      `json:"type_get_irregular_profile"`
}

// JobActionGetLimiterSchema defines model for JobActionGetLimiterSchema.
type JobActionGetLimiterSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id             ActionID `json:"id"`
	TypeGetLimiter int      `json:"type_get_limiter"`
}

// JobActionGetPeriodicalProfileSchema defines model for JobActionGetPeriodicalProfileSchema.
type JobActionGetPeriodicalProfileSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id ActionID `json:"id"`

	// ParamTfrom The start time of the profile data.
	ParamTfrom *time.Time `json:"param_tfrom,omitempty"`

	// ParamTto The end time of the profile data.
	ParamTto                 *time.Time `json:"param_tto,omitempty"`
	TypeGetPeriodicalProfile int        `json:"type_get_periodical_profile"`
}

// JobActionGetRegisterSchema defines model for JobActionGetRegisterSchema.
type JobActionGetRegisterSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id              ActionID `json:"id"`
	TypeGetRegister int      `json:"type_get_register"`
}

// JobActionGetRelayStateSchema defines model for JobActionGetRelayStateSchema.
type JobActionGetRelayStateSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                ActionID `json:"id"`
	TypeGetRelayState int      `json:"type_get_relay_state"`
}

// JobActionGetTouSchema defines model for JobActionGetTouSchema.
type JobActionGetTouSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id         ActionID `json:"id"`
	TypeGetTou int      `json:"type_get_tou"`
}

// JobActionListSchema List of actions to be queued. The empty array is not valid, at least one action must be present. The actions are processed in the order they are defined in the list.
type JobActionListSchema = []JobActionSchema

// JobActionResetBillingPeriodSchema defines model for JobActionResetBillingPeriodSchema.
type JobActionResetBillingPeriodSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                     ActionID `json:"id"`
	TypeResetBillingPeriod int      `json:"type_reset_billing_period"`
}

// JobActionResultSchema defines model for JobActionResultSchema.
type JobActionResultSchema struct {
	// Code The result of the action. If the action was successful, the value is true and vice versa.
	//   * `OK` - The action has been successfully processed.
	//   * `UNSUPPORTED` - The action is not supported by the driver.
	//   * `ERROR` - Some error(s) have occurred during the processing of the action.
	//   * `NOT_PROCESSED` - The action has not been processed.
	Code JobActionResultSchemaCode `json:"code"`

	// Data The result data of the action.
	Data JobActionResultSchema_Data `json:"data"`

	// Id The ID of the action.
	Id ActionID `json:"id"`
}

// JobActionResultSchemaCode The result of the action. If the action was successful, the value is true and vice versa.
//   - `OK` - The action has been successfully processed.
//   - `UNSUPPORTED` - The action is not supported by the driver.
//   - `ERROR` - Some error(s) have occurred during the processing of the action.
//   - `NOT_PROCESSED` - The action has not been processed.
type JobActionResultSchemaCode string

// JobActionResultSchema_Data The result data of the action.
type JobActionResultSchema_Data struct {
	union json.RawMessage
}

// JobActionSchema Schema that holds the action definition.
type JobActionSchema struct {
	union json.RawMessage
}

// JobActionSetDisconnectorStateSchema defines model for JobActionSetDisconnectorStateSchema.
type JobActionSetDisconnectorStateSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                       ActionID `json:"id"`
	TypeSetDisconnectorState int      `json:"type_set_disconnector_state"`
}

// JobActionSetLimiterSchema defines model for JobActionSetLimiterSchema.
type JobActionSetLimiterSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id             ActionID `json:"id"`
	TypeSetLimiter int      `json:"type_set_limiter"`
}

// JobActionSetRelayStateSchema defines model for JobActionSetRelayStateSchema.
type JobActionSetRelayStateSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                ActionID `json:"id"`
	TypeSetRelayState int      `json:"type_set_relay_state"`
}

// JobActionSetTouSchema defines model for JobActionSetTouSchema.
type JobActionSetTouSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id         ActionID `json:"id"`
	TypeSetTou int      `json:"type_set_tou"`
}

// JobActionSyncClockSchema defines model for JobActionSyncClockSchema.
type JobActionSyncClockSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id            ActionID `json:"id"`
	TypeSyncClock int      `json:"type_sync_clock"`
}

// JobDeviceListSchema List of devices to be queued.
type JobDeviceListSchema = []JobDeviceSchema

// JobDeviceSchema defines model for JobDeviceSchema.
type JobDeviceSchema struct {
	ConnectionInfo ConnectionTypeSchema `json:"connectionInfo"`

	// DeviceAttributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	DeviceAttributes AttributesSchema `json:"deviceAttributes"`

	// ExternalID The public ID of the device.
	ExternalID *string `json:"externalID"`

	// Id The ID of the job. The ID must be unique across the OpenHES components.
	Id JobID `json:"id"`
}

// JobErrorCodeSchema The result of the job.
//   - `NONE` - No error, the job has been successfully processed.
//   - `ERROR` - Some error(s) have occurred during the processing of the job.
//   - `FATAL` - The job could not be processed due to a fatal error.
type JobErrorCodeSchema string

// JobID The ID of the job. The ID must be unique across the OpenHES components.
type JobID = openapi_types.UUID

// JobSettingsSchema Schema that holds the settings of the job.
type JobSettingsSchema struct {
	// Attempts Number of attempts to process the job.
	Attempts *int32 `json:"attempts,omitempty"`

	// DeferStart Delay in seconds before starting the first attempt of the job.
	DeferStart *int64 `json:"deferStart,omitempty"`

	// ExpiresAt Time when the job expires.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// MaxDuration Maximum duration in seconds to process the job.
	MaxDuration *int64 `json:"maxDuration,omitempty"`

	// Priority Priority of the job.
	Priority *int32 `json:"priority,omitempty"`

	// RetryDelay Delay in seconds before retrying the job.
	RetryDelay *int64 `json:"retryDelay,omitempty"`
}

// JobStatusCodeEnumSchema The status of the job.
type JobStatusCodeEnumSchema int

// JobStatusSchema Schema that holds the status of the job.
type JobStatusSchema struct {
	// Code The result of the job.
	//   * `NONE` - No error, the job has been successfully processed.
	//   * `ERROR` - Some error(s) have occurred during the processing of the job.
	//   * `FATAL` - The job could not be processed due to a fatal error.
	Code JobErrorCodeSchema `json:"code"`

	// FinishedAt The time when the driver finished processing the job.
	FinishedAt *time.Time `json:"finishedAt"`

	// Results The results of the actions. If an action has not been processed, the result is not present.
	Results *[]JobActionResultSchema `json:"results"`

	// StartedAt The time when the driver started processing the job.
	StartedAt *time.Time `json:"startedAt"`

	// Status The status of the job.
	Status JobStatusCodeEnumSchema `json:"status"`
}

// AsConnectionTypeTcpSchema returns the union data inside the ConnectionTypeSchema as a ConnectionTypeTcpSchema
func (t ConnectionTypeSchema) AsConnectionTypeTcpSchema() (ConnectionTypeTcpSchema, error) {
	var body ConnectionTypeTcpSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConnectionTypeTcpSchema overwrites any union data inside the ConnectionTypeSchema as the provided ConnectionTypeTcpSchema
func (t *ConnectionTypeSchema) FromConnectionTypeTcpSchema(v ConnectionTypeTcpSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConnectionTypeTcpSchema performs a merge with any union data inside the ConnectionTypeSchema, using the provided ConnectionTypeTcpSchema
func (t *ConnectionTypeSchema) MergeConnectionTypeTcpSchema(v ConnectionTypeTcpSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConnectionTypePhoneSchema returns the union data inside the ConnectionTypeSchema as a ConnectionTypePhoneSchema
func (t ConnectionTypeSchema) AsConnectionTypePhoneSchema() (ConnectionTypePhoneSchema, error) {
	var body ConnectionTypePhoneSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConnectionTypePhoneSchema overwrites any union data inside the ConnectionTypeSchema as the provided ConnectionTypePhoneSchema
func (t *ConnectionTypeSchema) FromConnectionTypePhoneSchema(v ConnectionTypePhoneSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConnectionTypePhoneSchema performs a merge with any union data inside the ConnectionTypeSchema, using the provided ConnectionTypePhoneSchema
func (t *ConnectionTypeSchema) MergeConnectionTypePhoneSchema(v ConnectionTypePhoneSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConnectionTypeSerialSchema returns the union data inside the ConnectionTypeSchema as a ConnectionTypeSerialSchema
func (t ConnectionTypeSchema) AsConnectionTypeSerialSchema() (ConnectionTypeSerialSchema, error) {
	var body ConnectionTypeSerialSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConnectionTypeSerialSchema overwrites any union data inside the ConnectionTypeSchema as the provided ConnectionTypeSerialSchema
func (t *ConnectionTypeSchema) FromConnectionTypeSerialSchema(v ConnectionTypeSerialSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConnectionTypeSerialSchema performs a merge with any union data inside the ConnectionTypeSchema, using the provided ConnectionTypeSerialSchema
func (t *ConnectionTypeSchema) MergeConnectionTypeSerialSchema(v ConnectionTypeSerialSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ConnectionTypeSchema) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ConnectionTypeSchema) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsExternalRef0DeviceRegistersDataSchema returns the union data inside the JobActionResultSchema_Data as a externalRef0.DeviceRegistersDataSchema
func (t JobActionResultSchema_Data) AsExternalRef0DeviceRegistersDataSchema() (externalRef0.DeviceRegistersDataSchema, error) {
	var body externalRef0.DeviceRegistersDataSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExternalRef0DeviceRegistersDataSchema overwrites any union data inside the JobActionResultSchema_Data as the provided externalRef0.DeviceRegistersDataSchema
func (t *JobActionResultSchema_Data) FromExternalRef0DeviceRegistersDataSchema(v externalRef0.DeviceRegistersDataSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExternalRef0DeviceRegistersDataSchema performs a merge with any union data inside the JobActionResultSchema_Data, using the provided externalRef0.DeviceRegistersDataSchema
func (t *JobActionResultSchema_Data) MergeExternalRef0DeviceRegistersDataSchema(v externalRef0.DeviceRegistersDataSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsExternalRef0DeviceProfileDataSchema returns the union data inside the JobActionResultSchema_Data as a externalRef0.DeviceProfileDataSchema
func (t JobActionResultSchema_Data) AsExternalRef0DeviceProfileDataSchema() (externalRef0.DeviceProfileDataSchema, error) {
	var body externalRef0.DeviceProfileDataSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExternalRef0DeviceProfileDataSchema overwrites any union data inside the JobActionResultSchema_Data as the provided externalRef0.DeviceProfileDataSchema
func (t *JobActionResultSchema_Data) FromExternalRef0DeviceProfileDataSchema(v externalRef0.DeviceProfileDataSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExternalRef0DeviceProfileDataSchema performs a merge with any union data inside the JobActionResultSchema_Data, using the provided externalRef0.DeviceProfileDataSchema
func (t *JobActionResultSchema_Data) MergeExternalRef0DeviceProfileDataSchema(v externalRef0.DeviceProfileDataSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t JobActionResultSchema_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *JobActionResultSchema_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsJobActionGetRegisterSchema returns the union data inside the JobActionSchema as a JobActionGetRegisterSchema
func (t JobActionSchema) AsJobActionGetRegisterSchema() (JobActionGetRegisterSchema, error) {
	var body JobActionGetRegisterSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetRegisterSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetRegisterSchema
func (t *JobActionSchema) FromJobActionGetRegisterSchema(v JobActionGetRegisterSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetRegisterSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetRegisterSchema
func (t *JobActionSchema) MergeJobActionGetRegisterSchema(v JobActionGetRegisterSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetPeriodicalProfileSchema returns the union data inside the JobActionSchema as a JobActionGetPeriodicalProfileSchema
func (t JobActionSchema) AsJobActionGetPeriodicalProfileSchema() (JobActionGetPeriodicalProfileSchema, error) {
	var body JobActionGetPeriodicalProfileSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetPeriodicalProfileSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetPeriodicalProfileSchema
func (t *JobActionSchema) FromJobActionGetPeriodicalProfileSchema(v JobActionGetPeriodicalProfileSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetPeriodicalProfileSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetPeriodicalProfileSchema
func (t *JobActionSchema) MergeJobActionGetPeriodicalProfileSchema(v JobActionGetPeriodicalProfileSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetIrregularProfileSchema returns the union data inside the JobActionSchema as a JobActionGetIrregularProfileSchema
func (t JobActionSchema) AsJobActionGetIrregularProfileSchema() (JobActionGetIrregularProfileSchema, error) {
	var body JobActionGetIrregularProfileSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetIrregularProfileSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetIrregularProfileSchema
func (t *JobActionSchema) FromJobActionGetIrregularProfileSchema(v JobActionGetIrregularProfileSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetIrregularProfileSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetIrregularProfileSchema
func (t *JobActionSchema) MergeJobActionGetIrregularProfileSchema(v JobActionGetIrregularProfileSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetEventsSchema returns the union data inside the JobActionSchema as a JobActionGetEventsSchema
func (t JobActionSchema) AsJobActionGetEventsSchema() (JobActionGetEventsSchema, error) {
	var body JobActionGetEventsSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetEventsSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetEventsSchema
func (t *JobActionSchema) FromJobActionGetEventsSchema(v JobActionGetEventsSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetEventsSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetEventsSchema
func (t *JobActionSchema) MergeJobActionGetEventsSchema(v JobActionGetEventsSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetClockSchema returns the union data inside the JobActionSchema as a JobActionGetClockSchema
func (t JobActionSchema) AsJobActionGetClockSchema() (JobActionGetClockSchema, error) {
	var body JobActionGetClockSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetClockSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetClockSchema
func (t *JobActionSchema) FromJobActionGetClockSchema(v JobActionGetClockSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetClockSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetClockSchema
func (t *JobActionSchema) MergeJobActionGetClockSchema(v JobActionGetClockSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionSyncClockSchema returns the union data inside the JobActionSchema as a JobActionSyncClockSchema
func (t JobActionSchema) AsJobActionSyncClockSchema() (JobActionSyncClockSchema, error) {
	var body JobActionSyncClockSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionSyncClockSchema overwrites any union data inside the JobActionSchema as the provided JobActionSyncClockSchema
func (t *JobActionSchema) FromJobActionSyncClockSchema(v JobActionSyncClockSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionSyncClockSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSyncClockSchema
func (t *JobActionSchema) MergeJobActionSyncClockSchema(v JobActionSyncClockSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetRelayStateSchema returns the union data inside the JobActionSchema as a JobActionGetRelayStateSchema
func (t JobActionSchema) AsJobActionGetRelayStateSchema() (JobActionGetRelayStateSchema, error) {
	var body JobActionGetRelayStateSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetRelayStateSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetRelayStateSchema
func (t *JobActionSchema) FromJobActionGetRelayStateSchema(v JobActionGetRelayStateSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetRelayStateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetRelayStateSchema
func (t *JobActionSchema) MergeJobActionGetRelayStateSchema(v JobActionGetRelayStateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionSetRelayStateSchema returns the union data inside the JobActionSchema as a JobActionSetRelayStateSchema
func (t JobActionSchema) AsJobActionSetRelayStateSchema() (JobActionSetRelayStateSchema, error) {
	var body JobActionSetRelayStateSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionSetRelayStateSchema overwrites any union data inside the JobActionSchema as the provided JobActionSetRelayStateSchema
func (t *JobActionSchema) FromJobActionSetRelayStateSchema(v JobActionSetRelayStateSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionSetRelayStateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSetRelayStateSchema
func (t *JobActionSchema) MergeJobActionSetRelayStateSchema(v JobActionSetRelayStateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetDisconnectorStateSchema returns the union data inside the JobActionSchema as a JobActionGetDisconnectorStateSchema
func (t JobActionSchema) AsJobActionGetDisconnectorStateSchema() (JobActionGetDisconnectorStateSchema, error) {
	var body JobActionGetDisconnectorStateSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetDisconnectorStateSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetDisconnectorStateSchema
func (t *JobActionSchema) FromJobActionGetDisconnectorStateSchema(v JobActionGetDisconnectorStateSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetDisconnectorStateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetDisconnectorStateSchema
func (t *JobActionSchema) MergeJobActionGetDisconnectorStateSchema(v JobActionGetDisconnectorStateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionSetDisconnectorStateSchema returns the union data inside the JobActionSchema as a JobActionSetDisconnectorStateSchema
func (t JobActionSchema) AsJobActionSetDisconnectorStateSchema() (JobActionSetDisconnectorStateSchema, error) {
	var body JobActionSetDisconnectorStateSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionSetDisconnectorStateSchema overwrites any union data inside the JobActionSchema as the provided JobActionSetDisconnectorStateSchema
func (t *JobActionSchema) FromJobActionSetDisconnectorStateSchema(v JobActionSetDisconnectorStateSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionSetDisconnectorStateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSetDisconnectorStateSchema
func (t *JobActionSchema) MergeJobActionSetDisconnectorStateSchema(v JobActionSetDisconnectorStateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetTouSchema returns the union data inside the JobActionSchema as a JobActionGetTouSchema
func (t JobActionSchema) AsJobActionGetTouSchema() (JobActionGetTouSchema, error) {
	var body JobActionGetTouSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetTouSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetTouSchema
func (t *JobActionSchema) FromJobActionGetTouSchema(v JobActionGetTouSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetTouSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetTouSchema
func (t *JobActionSchema) MergeJobActionGetTouSchema(v JobActionGetTouSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionSetTouSchema returns the union data inside the JobActionSchema as a JobActionSetTouSchema
func (t JobActionSchema) AsJobActionSetTouSchema() (JobActionSetTouSchema, error) {
	var body JobActionSetTouSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionSetTouSchema overwrites any union data inside the JobActionSchema as the provided JobActionSetTouSchema
func (t *JobActionSchema) FromJobActionSetTouSchema(v JobActionSetTouSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionSetTouSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSetTouSchema
func (t *JobActionSchema) MergeJobActionSetTouSchema(v JobActionSetTouSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetLimiterSchema returns the union data inside the JobActionSchema as a JobActionGetLimiterSchema
func (t JobActionSchema) AsJobActionGetLimiterSchema() (JobActionGetLimiterSchema, error) {
	var body JobActionGetLimiterSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetLimiterSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetLimiterSchema
func (t *JobActionSchema) FromJobActionGetLimiterSchema(v JobActionGetLimiterSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetLimiterSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetLimiterSchema
func (t *JobActionSchema) MergeJobActionGetLimiterSchema(v JobActionGetLimiterSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionSetLimiterSchema returns the union data inside the JobActionSchema as a JobActionSetLimiterSchema
func (t JobActionSchema) AsJobActionSetLimiterSchema() (JobActionSetLimiterSchema, error) {
	var body JobActionSetLimiterSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionSetLimiterSchema overwrites any union data inside the JobActionSchema as the provided JobActionSetLimiterSchema
func (t *JobActionSchema) FromJobActionSetLimiterSchema(v JobActionSetLimiterSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionSetLimiterSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSetLimiterSchema
func (t *JobActionSchema) MergeJobActionSetLimiterSchema(v JobActionSetLimiterSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionResetBillingPeriodSchema returns the union data inside the JobActionSchema as a JobActionResetBillingPeriodSchema
func (t JobActionSchema) AsJobActionResetBillingPeriodSchema() (JobActionResetBillingPeriodSchema, error) {
	var body JobActionResetBillingPeriodSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionResetBillingPeriodSchema overwrites any union data inside the JobActionSchema as the provided JobActionResetBillingPeriodSchema
func (t *JobActionSchema) FromJobActionResetBillingPeriodSchema(v JobActionResetBillingPeriodSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionResetBillingPeriodSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionResetBillingPeriodSchema
func (t *JobActionSchema) MergeJobActionResetBillingPeriodSchema(v JobActionResetBillingPeriodSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionFwUpdateSchema returns the union data inside the JobActionSchema as a JobActionFwUpdateSchema
func (t JobActionSchema) AsJobActionFwUpdateSchema() (JobActionFwUpdateSchema, error) {
	var body JobActionFwUpdateSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionFwUpdateSchema overwrites any union data inside the JobActionSchema as the provided JobActionFwUpdateSchema
func (t *JobActionSchema) FromJobActionFwUpdateSchema(v JobActionFwUpdateSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionFwUpdateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionFwUpdateSchema
func (t *JobActionSchema) MergeJobActionFwUpdateSchema(v JobActionFwUpdateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t JobActionSchema) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *JobActionSchema) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xb3XPjthH/VzBoH9oObd9HLu35qT5Zd1WiSKokp82kNw5EriTkSIABQPvUjP/3Dj5I",
	"8QMUqbN0D32yTACL3R8Wi93F4ncc8iTlDJiS+Pp3LMMtJMT8vAkV5Wx0q39HIENBU/0BX+PlFtDoFvE1",
	"UltAxPS7/A/DAV5zkRCFr3GW0QgHWO1SwNdYKkHZBj8Fjuhyl8LCzOQnrodp8gVphP6CfvkwXN7Phx9G",
	"i+Vw/gu6QMtickQlUhxtQKEVjWPKNuiBxBkEaM0Fgs8kSWNAlElFmCIMeCZtB1mmPRvOR9Pb0eBmfD+b",
	"T9+PxsPWWVIQlEc0JDFKBV/TuDZVzEl04VrKU4zm8+GHu/HNvHMGxtlF1ywRofEub0JcoIQztY13BQgC",
	"NlQqEBUxhz8OJ8tF68TwAEyhmG/KYwbj6eD71iFaC8KYh5/yIYufJoMDY+SOhVvBGf0vlMaW+5V6yH0X",
	"RJn5J4IHGkKAqEIhYRqSENZZHO+QBKW/0rX9iIhSgq4yBXpmCaqqSuObn+4Xy5vl8KBkAmKyQ1IRVSzl",
	"osdw2T5cz347Wgymk8lwsJzOezARURlyxiBUXDR56UlMdhLTnC2ndwdZUTSBC76+yCQgRVZxhZO2wbJr",
	"sJ55PPphdGhvawIxTagCoQkqyjayPPmh8bJj/HyoKbwbjcejyQdnCryEBMiSmbFbNCfy/l/3d7PbVvgV",
	"EQqtqUgeiQCUpZFFHgcYWJbg659x2cThAPutkmto2BL33e5v94/ZhDjA+x3pGkrqq5sbX/w66rp6G5zu",
	"uC72V2lV3ff9fz7EcYALDPFH3/mRb2i5Pz9IFFENM4lngqcgFAVzgBG2m67x9c+/N8gUXyhTsAFR/sSy",
	"ZFX9suI8BsLw08cAsyyOtdriayUyeApqh5dlCqktUWjL40giYjRPn2UF54iwSOsiFfkhZHTlE+yMomxB",
	"m3Qtxw4xkkDe3XZudDFfLQXbQZvElTk+zTFqhQ6QEzVAVsAAObECtKKMiF2gDxAtntVIJztf/QqhwgH+",
	"fLHhF+5jIcrlfjnKXS5oknKh9BqkRG3xNd5Qtc1WlyFPrsLdSnAZk5W82oK8eHVBUiqveAqMpNT83YK8",
	"KqbAT08BfpfFn7odkVUWf0K/8pUFY3SLkkwqDUXG6G+Z3oyCS4veNAX2j+EC7Z2fnv6L5mSRQtjmvTQV",
	"QE/HmTueBWgGpTnFJWUbfYgL+gDCrJXlIa0qsbEg5ucfBazxNf7D1Z7rK+evXX3HV9a1GlOpHHNPAQ65",
	"0OfPIUeu1KWGpcWx1k4lyiRExiQLnqVFb4dgdYN4ELSHdx+Bbk3PqkAWraUh6pOmhKY5eZVlVTNZaIZp",
	"zHXDLI2VWWapVluIylScWAllY2AbrcwvPULRqEsep8JPAc5Pnh4ILFzXvfyPsNpy/uluPvbLfzcf5+K4",
	"rvbwcyaEcUXXNLSr+bgFhgjbaWRy18rsISpRxBnUt4Sg3ev7FGABv2VUQKTPM7OJ8hUPCmWurOPHurHJ",
	"t5kiKpNDliWHQgVpelXUdn+evgheBq+C18E3+zlyi6/Nle51USIpNcvLEgq/ZZBBZHZrKngIUu9ZrUTa",
	"m7QTU4lILK1/QdbasyBKQZIqtCY0lpqZMsUwEwKY0j46GP/BkoWo0ZFrF1/VGrZEohUA00Y+hDj2NMPn",
	"VKN/qXF1Ij4QoQ8SI94/74Z3Q33Ozu8mk9HkAw7wYPrDbDxcmq+Dm8lgOB6b38N/z0bz4S3+WFmQ4yxf",
	"c3n0b20DLxumbk0ZlVuIblRLVEgTsEqrGngkRHyCCJEycFX11c7WhSbRx0gZV+3LOPHrzPN4UZnsY18a",
	"O6a+HR0p344b2IDABeezLWdw3EqneggKCzKIsjX3nWjOwfICa4nYHrnSWPPRwwzXhHXzdAu7l5MzcB7j",
	"Iairo5dhWpjnY8aVIT5u5AIEJXE+9GNTnnL7//3q7fHvKepyMOsj6JbLlt0/miESRQKk1E6d7mfcdI/A",
	"jb2cu8Ue7LhQh6Ajn2miz7Rv37x5/cZAaf9/2TjZ6kgaQdzUPjitmzWzWaR3MQ8/HWnirR8bcqYoy3gm",
	"0coka/i6SE1FRBEfxsbMtp7rQllDmx8eLsPUZkgbYNvgqstwNsX/0YwrmdAekFXG9AQuplKVUSoykjjA",
	"VEHSyfoHYCBoaOauHM57nokQZOdn+ZncmuU4httWPevi9pYocqQ169A7y/vxDJfwtYmflr1s2nK9LTOj",
	"3WwJIWdRPeCkTL1+hZubOcAZoy17RLf4ZvEan5pVcBA48oU87QZi7nLJx69GnoVuXQ69gaUiSdrubZnm",
	"wjAWdPoZgn4ItiLnLMmX78anTlDl8ajm+7Gc4z9uK3pW1LMVW8U67niwualHqraIqiJ6IizSAYthz6cZ",
	"eZt/9fLWfAVtKqzvvtr71V1RZQvdb7/x0i2UpUm2RGjvajaTk92TlPpEPNPRQ9Anf+nVxCJ1NOBJwlnb",
	"6tpWtKagV1ZuiXBRDoljl+eW3gTWPkXYoZWN3G6vxEpxTenNPZRm/3hI9vePdyYdX8oqx3GPWMAPnga/",
	"ZuJ2KdyvH+9t0l9/KTy6l0d5czVCTaE+Br22pbuZiEBH3eZn6w1FBagPoAZVH/EMQG1A3Zsbv+cCtSd0",
	"WqA2oNytZR2c29LdmjaXcHagyrd59+Y27xSoeaieHkLPRWQdz+GDRufsIJpbb3kK4Byl04NlCTcAGgkB",
	"mywmwjmqZ4eK5hPeO5/zFKg1iZ4ewGKO3FluYDm2l8Nnh9BdQp8CuJzU6eFq3JTX0ZoV5SlnVr2UCJLc",
	"q7XgSd9kQTMc6hcquKkUb/E4WXSSaYrl25f4nHI3eaieXj+a1UkNDckjjLNvqDwIOgV4Ba3TQ5aT9gAV",
	"k93XcRdMPdLp/IQyuXMAti+eqmO25NnZwVI8OwVImszpwWnWUlUgKl2cN2zZ2CUPXNymKa7AXV3ZS3JI",
	"UrVDJguAqESMKx290ihARKEYiB7PCuby2/RUgNShfKn4SSIdShT3nPlFMxcRCP1rZ9qNdPvWmEp1RD6j",
	"kHkfOHrvGoqkRjFgDhLUO1vMZc+zs+qUKR67d8Vj9/sc4nMUzEvztNrmrXmr45jFJXWryh7yqCUjIsy4",
	"WikxGpX/RY9EIpmFWn/WWRzUaqFEZiukHmgI6AGEJHk13rRefVrc0e6p2fpZdwXvxt1NFnez2XS+HHoq",
	"APVG2BeKrHY2dWiqGfLxw/l8aooQFzwBBEJw8Sf5Z7QlD4B4aCoAIhRl2hfInQh3TdwoqTb0JtPl/Ww+",
	"HQwXiwZHWiTNkhGrLEmpqHD6PQ5wSSgcYMMiDnCFtLfgTns2B5fOpLU9peD97lLb06Bdd6JtVwTmQvS5",
	"aSOjsE74g3mj43Khjc112RuoA25VF1J9fPZjaLREnMeQqET1xwwcVO6N+p4KOxZ+0UCfZ9Z/1ucMPpBJ",
	"OoaBZ9Oo+FnHzPwFoxoB+DHzfeHI1vO/N4Va5tiYnz5LcB4HQ54lISi/RkJQ9kgILr5OjkaeLkcjz5aj",
	"kZ05msVXCyzlaQNLedbAUh4KLBfnDyzlaQJLeZbAUnYHlvXj9Ewo7Vh4mkugEqUTY7VjYfUaqFGy3hp5",
	"u6LoauR9VMRr5zoi4q0M8MRoeUnciK151/zeCsqiuv/mWXe+8FmBYCRue7GQZquYhqXHCuVCuc5y2u7Q",
	"4Du+ao8LKiB55G2JFoY6Chzw6OCz12ow/Ctf7SPAiXlSNuE2nAzyDn1D2ueHpCVu3t8sb8Z5HKqZCHkW",
	"Ry4MLWV6ogy0ehO0JorEdtZqZKrlKkWjhrA3CrVL0vH+58xPf5rvMfpWwLhRVSh9hRKQpMpTkTIpykLz",
	"PhpXB3RB0lf1UpjNt28P202tyWvQDqqvIPPWnJb72jW0gjUX7t4l15k1FVIVrx9KsvrKZgrG/vbtNy9e",
	"lHh74ePNvmmQ3nL8Sim+1kbX+bL3ZUxCPt9mgliCdfo/WEb15iCuXrhAoXsRqrL+9VVF1JdvfLKmgnJB",
	"1a7Jysy1HMC2tuhduApQYmcWt/+amzH5mneK/PZtBxMtFUm20kwbzOMeADmGnvn+xzyIOuXzH0ew8/VP",
	"3q/++Kdi6htvf/LW8zz9KVbjOS9/3Lr408Idh3H97HwKjnwq5J7z5YPKp1vFHn/Z+xx7astDR7qsJkil",
	"yXATdjiJG7jiWeMTuMxzfr/yBVcjlQz9U6tchcN41BMoh7Abc2KA+z2AajMaLW+gXI636a7p/tR5wCFn",
	"ioQGAUgIjY39WPO/798wX4Y80TKQRNMYmO9oTFYSKSC6JRN61FapVF5fXT0+Pl5WB19RFoHerJdblcRa",
	"3JiGwKTZGI7su8X44uXliwY1ngKTPBMhXHKxuXID5VXeX9tWqmLYV2/ezEYo4RHE9gmy84VwgB9ASLu4",
	"Ly7dUPckG1/j15d29pSorcTXesGe/hcAAP//xHTSyjlGAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../driver/driverdata/driverdata.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
