// Package job provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package job

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/cybroslabs/hes-2-apis/openapi/openhes/device"
	externalRef1 "github.com/cybroslabs/hes-2-apis/openapi/openhes/driver"
	externalRef2 "github.com/cybroslabs/hes-2-apis/openapi/openhes/driver/driverdata"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BulkStatusEnumSchema.
const (
	BulkStatusEnumSchemaCANCELLED BulkStatusEnumSchema = 3
	BulkStatusEnumSchemaCOMPLETED BulkStatusEnumSchema = 2
	BulkStatusEnumSchemaEXPIRED   BulkStatusEnumSchema = 4
	BulkStatusEnumSchemaQUEUED    BulkStatusEnumSchema = 0
	BulkStatusEnumSchemaRUNNING   BulkStatusEnumSchema = 1
)

// Defines values for JobActionResultSchemaCode.
const (
	JobActionResultSchemaCodeERROR        JobActionResultSchemaCode = "ERROR"
	JobActionResultSchemaCodeNOTPROCESSED JobActionResultSchemaCode = "NOT_PROCESSED"
	JobActionResultSchemaCodeOK           JobActionResultSchemaCode = "OK"
	JobActionResultSchemaCodeUNSUPPORTED  JobActionResultSchemaCode = "UNSUPPORTED"
)

// Defines values for JobCustomDeviceListTypedSchemaListType.
const (
	JOBDEVICESFULL JobCustomDeviceListTypedSchemaListType = "JOBDEVICESFULL"
)

// Defines values for JobDeviceListTypedSchemaListType.
const (
	JOBDEVICESID JobDeviceListTypedSchemaListType = "JOBDEVICESID"
)

// Defines values for JobErrorCodeSchema.
const (
	JobErrorCodeSchemaERROR JobErrorCodeSchema = "ERROR"
	JobErrorCodeSchemaFATAL JobErrorCodeSchema = "FATAL"
	JobErrorCodeSchemaNONE  JobErrorCodeSchema = "NONE"
)

// Defines values for JobStatusCodeEnumSchema.
const (
	JobStatusCodeEnumSchemaCANCELLED JobStatusCodeEnumSchema = 3
	JobStatusCodeEnumSchemaCOMPLETED JobStatusCodeEnumSchema = 2
	JobStatusCodeEnumSchemaEXPIRED   JobStatusCodeEnumSchema = 4
	JobStatusCodeEnumSchemaQUEUED    JobStatusCodeEnumSchema = 0
	JobStatusCodeEnumSchemaRUNNING   JobStatusCodeEnumSchema = 1
)

// ActionID The ID of the action.
type ActionID = openapi_types.UUID

// BulkID The ID of the job bulk. The ID must be unique across all OpenHES components.
type BulkID = openapi_types.UUID

// BulkSpecSchema Schema that describes jobs for a specific driver type.
type BulkSpecSchema struct {
	// Actions A list of actions to be processed. An empty array is not valid, at least one action must be present. The actions are processed in the same order as they are defined in the list.
	Actions JobActionListSchema `json:"actions"`

	// CorrelationID The correlation ID of the bulk. The correlation ID is used to group bulks.
	CorrelationID *string                `json:"correlationID"`
	Devices       BulkSpecSchema_Devices `json:"devices"`

	// DriverType The driver type related to the job. The type must be one of the supported driver types.
	DriverType string `json:"driverType"`

	// Id The ID of the job bulk. The ID must be unique across all OpenHES components.
	Id BulkID `json:"id"`

	// Settings Schema that describes job settings.
	Settings *JobSettingsSchema `json:"settings,omitempty"`

	// WebhookURL The URL of the webhook to send a notification when any job in the bulk is done.
	WebhookURL *string `json:"webhookURL"`
}

// BulkSpecSchema_Devices defines model for BulkSpecSchema.Devices.
type BulkSpecSchema_Devices struct {
	Union json.RawMessage
}

// BulkStatusEnumSchema The status of a bulk.
type BulkStatusEnumSchema int

// BulkStatusSchema Schema that describes the bulk status.
type BulkStatusSchema struct {
	// FinishedAt The time when the bulk has been marked as completed.
	FinishedAt *time.Time `json:"finishedAt"`

	// StartedAt The time when the bulk has been queued for processing.
	StartedAt *time.Time `json:"startedAt"`

	// Status The status of a bulk.
	Status BulkStatusEnumSchema `json:"status"`
}

// JobActionCommonSchema Common fields shared for all actions.
type JobActionCommonSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id ActionID `json:"id"`
}

// JobActionFwUpdateSchema defines model for JobActionFwUpdateSchema.
type JobActionFwUpdateSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id           ActionID `json:"id"`
	TypeFwUpdate int      `json:"type_fw_update"`
}

// JobActionGetClockSchema defines model for JobActionGetClockSchema.
type JobActionGetClockSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id           ActionID `json:"id"`
	TypeGetClock int      `json:"type_get_clock"`
}

// JobActionGetDisconnectorStateSchema defines model for JobActionGetDisconnectorStateSchema.
type JobActionGetDisconnectorStateSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                       ActionID `json:"id"`
	TypeGetDisconnectorState int      `json:"type_get_disconnector_state"`
}

// JobActionGetEventsSchema defines model for JobActionGetEventsSchema.
type JobActionGetEventsSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id            ActionID `json:"id"`
	TypeGetEvents int      `json:"type_get_events"`
}

// JobActionGetIrregularProfileSchema defines model for JobActionGetIrregularProfileSchema.
type JobActionGetIrregularProfileSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                      ActionID `json:"id"`
	TypeGetIrregularProfile int      `json:"type_get_irregular_profile"`
}

// JobActionGetLimiterSchema defines model for JobActionGetLimiterSchema.
type JobActionGetLimiterSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id             ActionID `json:"id"`
	TypeGetLimiter int      `json:"type_get_limiter"`
}

// JobActionGetPeriodicalProfileSchema defines model for JobActionGetPeriodicalProfileSchema.
type JobActionGetPeriodicalProfileSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id ActionID `json:"id"`

	// ParamTfrom The start time of the profile data.
	ParamTfrom *time.Time `json:"param_tfrom,omitempty"`

	// ParamTto The end time of the profile data.
	ParamTto                 *time.Time `json:"param_tto,omitempty"`
	TypeGetPeriodicalProfile int        `json:"type_get_periodical_profile"`
}

// JobActionGetRegisterSchema defines model for JobActionGetRegisterSchema.
type JobActionGetRegisterSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id              ActionID `json:"id"`
	TypeGetRegister int      `json:"type_get_register"`
}

// JobActionGetRelayStateSchema defines model for JobActionGetRelayStateSchema.
type JobActionGetRelayStateSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                ActionID `json:"id"`
	TypeGetRelayState int      `json:"type_get_relay_state"`
}

// JobActionGetTouSchema defines model for JobActionGetTouSchema.
type JobActionGetTouSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id         ActionID `json:"id"`
	TypeGetTou int      `json:"type_get_tou"`
}

// JobActionListSchema A list of actions to be processed. An empty array is not valid, at least one action must be present. The actions are processed in the same order as they are defined in the list.
type JobActionListSchema = []JobActionSchema

// JobActionResetBillingPeriodSchema defines model for JobActionResetBillingPeriodSchema.
type JobActionResetBillingPeriodSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                     ActionID `json:"id"`
	TypeResetBillingPeriod int      `json:"type_reset_billing_period"`
}

// JobActionResultSchema defines model for JobActionResultSchema.
type JobActionResultSchema struct {
	// Code The result of the action. If the action is successful, the value is true and vice versa.
	//   * `OK` - The action has been successfully processed.
	//   * `UNSUPPORTED` - The action is not supported by the driver.
	//   * `ERROR` - Some errors have occurred during the processing of the action.
	//   * `NOT_PROCESSED` - The action has not been processed.
	Code JobActionResultSchemaCode `json:"code"`

	// Data The result data of the action.
	Data JobActionResultSchema_Data `json:"data"`

	// Id The ID of the action.
	Id ActionID `json:"id"`
}

// JobActionResultSchemaCode The result of the action. If the action is successful, the value is true and vice versa.
//   - `OK` - The action has been successfully processed.
//   - `UNSUPPORTED` - The action is not supported by the driver.
//   - `ERROR` - Some errors have occurred during the processing of the action.
//   - `NOT_PROCESSED` - The action has not been processed.
type JobActionResultSchemaCode string

// JobActionResultSchema_Data The result data of the action.
type JobActionResultSchema_Data struct {
	Union json.RawMessage
}

// JobActionSchema Schema that describes actions.
type JobActionSchema struct {
	Union json.RawMessage
}

// JobActionSetDisconnectorStateSchema defines model for JobActionSetDisconnectorStateSchema.
type JobActionSetDisconnectorStateSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                       ActionID `json:"id"`
	TypeSetDisconnectorState int      `json:"type_set_disconnector_state"`
}

// JobActionSetLimiterSchema defines model for JobActionSetLimiterSchema.
type JobActionSetLimiterSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id             ActionID `json:"id"`
	TypeSetLimiter int      `json:"type_set_limiter"`
}

// JobActionSetRelayStateSchema defines model for JobActionSetRelayStateSchema.
type JobActionSetRelayStateSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                ActionID `json:"id"`
	TypeSetRelayState int      `json:"type_set_relay_state"`
}

// JobActionSetTouSchema defines model for JobActionSetTouSchema.
type JobActionSetTouSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id         ActionID `json:"id"`
	TypeSetTou int      `json:"type_set_tou"`
}

// JobActionSyncClockSchema defines model for JobActionSyncClockSchema.
type JobActionSyncClockSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id            ActionID `json:"id"`
	TypeSyncClock int      `json:"type_sync_clock"`
}

// JobCustomDeviceListSchema List of custom-devices to be queued.
type JobCustomDeviceListSchema = []JobCustomDeviceSchema

// JobCustomDeviceListTypedSchema defines model for JobCustomDeviceListTypedSchema.
type JobCustomDeviceListTypedSchema struct {
	// Items List of custom-devices to be queued.
	Items    JobCustomDeviceListSchema              `json:"items"`
	ListType JobCustomDeviceListTypedSchemaListType `json:"listType"`
}

// JobCustomDeviceListTypedSchemaListType defines model for JobCustomDeviceListTypedSchema.ListType.
type JobCustomDeviceListTypedSchemaListType string

// JobCustomDeviceSchema defines model for JobCustomDeviceSchema.
type JobCustomDeviceSchema struct {
	// ApplicationProtocol The type of the application layer.
	//   * `IEC_62056_21` - The IEC 62056-21 (IEC-61107, VDEW) protocol.
	//   * `DLMS_SN` - The DLMS short-name protocol.
	//   * `DLMS_LN` - The DLMS logical-name protocol.
	//   * `SCTM` - The SCTM protocol.
	//   * `LIS200` - The LIS200 protocol.
	//   * `ANSI_C12` - The ANSI C12 protocol.
	//   * `MQTT` - The MQTT protocol.
	//   * `MODBUS` - The Modbus protocol.
	ApplicationProtocol *externalRef1.ApplicationProtocolSchema `json:"applicationProtocol,omitempty"`

	// ConnectionInfo The connection information of the device.
	ConnectionInfo []externalRef0.ConnectionInfoSchema `json:"connectionInfo"`

	// DeviceAttributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	DeviceAttributes externalRef0.AttributesSchema `json:"deviceAttributes"`

	// ExternalID The public ID of the device.
	ExternalID *string `json:"externalID"`

	// Id The ID of the job. The ID must be unique across all OpenHES components.
	Id JobID `json:"id"`

	// Timezone The timezone of the device.
	Timezone *string `json:"timezone"`
}

// JobDeviceListSchema List of device identifiers to be queued, look for devices in device registry.
type JobDeviceListSchema = []JobDeviceSchema

// JobDeviceListTypedSchema defines model for JobDeviceListTypedSchema.
type JobDeviceListTypedSchema struct {
	// Items List of device identifiers to be queued, look for devices in device registry.
	Items    JobDeviceListSchema              `json:"items"`
	ListType JobDeviceListTypedSchemaListType `json:"listType"`
}

// JobDeviceListTypedSchemaListType defines model for JobDeviceListTypedSchema.ListType.
type JobDeviceListTypedSchemaListType string

// JobDeviceSchema defines model for JobDeviceSchema.
type JobDeviceSchema struct {
	// DeviceId The ID of the device.
	DeviceId openapi_types.UUID `json:"deviceId"`

	// Id The ID of the job. The ID must be unique across all OpenHES components.
	Id JobID `json:"id"`
}

// JobErrorCodeSchema The result of the job.
//   - `NONE` - No error, the job has been successfully processed.
//   - `ERROR` - Some error(s) have occurred during the processing of the job.
//   - `FATAL` - The job could not be processed due to a fatal error.
type JobErrorCodeSchema string

// JobID The ID of the job. The ID must be unique across all OpenHES components.
type JobID = openapi_types.UUID

// JobSettingsSchema Schema that describes job settings.
type JobSettingsSchema struct {
	// Attempts The number of attempts to process the job per communication unit. The default is [1].
	Attempts *[]int32 `json:"attempts,omitempty"`

	// DeferStart The delay in seconds before starting the first attempt of the job.
	DeferStart *int64 `json:"deferStart,omitempty"`

	// ExpiresAt The time when the job expires.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// MaxDuration The maximum duration in seconds to process the job.
	MaxDuration *int64 `json:"maxDuration,omitempty"`

	// Priority The priority of the job. The lower the value, the lower the priority.
	Priority *int32 `json:"priority,omitempty"`

	// RetryDelay The delay in seconds before retrying the job.
	RetryDelay *int64 `json:"retryDelay,omitempty"`
}

// JobStatusCodeEnumSchema The status of the job.
type JobStatusCodeEnumSchema int

// JobStatusSchema Schema that describes the status of a job.
type JobStatusSchema struct {
	// Code The result of the job.
	//   * `NONE` - No error, the job has been successfully processed.
	//   * `ERROR` - Some error(s) have occurred during the processing of the job.
	//   * `FATAL` - The job could not be processed due to a fatal error.
	Code JobErrorCodeSchema `json:"code"`

	// FinishedAt The time when the driver finished processing the job.
	FinishedAt *time.Time `json:"finishedAt"`

	// Results The results of the actions. If an action has not been processed, the result is not present.
	Results *[]JobActionResultSchema `json:"results"`

	// StartedAt The time when the driver started processing the job.
	StartedAt *time.Time `json:"startedAt"`

	// Status The status of the job.
	Status JobStatusCodeEnumSchema `json:"status"`
}

// AsJobCustomDeviceListTypedSchema returns the union data inside the BulkSpecSchema_Devices as a JobCustomDeviceListTypedSchema
func (t BulkSpecSchema_Devices) AsJobCustomDeviceListTypedSchema() (JobCustomDeviceListTypedSchema, error) {
	var body JobCustomDeviceListTypedSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobCustomDeviceListTypedSchema overwrites any union data inside the BulkSpecSchema_Devices as the provided JobCustomDeviceListTypedSchema
func (t *BulkSpecSchema_Devices) FromJobCustomDeviceListTypedSchema(v JobCustomDeviceListTypedSchema) error {
	v.ListType = "JOBDEVICESID"
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobCustomDeviceListTypedSchema performs a merge with any union data inside the BulkSpecSchema_Devices, using the provided JobCustomDeviceListTypedSchema
func (t *BulkSpecSchema_Devices) MergeJobCustomDeviceListTypedSchema(v JobCustomDeviceListTypedSchema) error {
	v.ListType = "JOBDEVICESID"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobDeviceListTypedSchema returns the union data inside the BulkSpecSchema_Devices as a JobDeviceListTypedSchema
func (t BulkSpecSchema_Devices) AsJobDeviceListTypedSchema() (JobDeviceListTypedSchema, error) {
	var body JobDeviceListTypedSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobDeviceListTypedSchema overwrites any union data inside the BulkSpecSchema_Devices as the provided JobDeviceListTypedSchema
func (t *BulkSpecSchema_Devices) FromJobDeviceListTypedSchema(v JobDeviceListTypedSchema) error {
	v.ListType = "JOBDEVICESFULL"
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobDeviceListTypedSchema performs a merge with any union data inside the BulkSpecSchema_Devices, using the provided JobDeviceListTypedSchema
func (t *BulkSpecSchema_Devices) MergeJobDeviceListTypedSchema(v JobDeviceListTypedSchema) error {
	v.ListType = "JOBDEVICESFULL"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

func (t BulkSpecSchema_Devices) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"listType"`
	}
	err := json.Unmarshal(t.Union, &discriminator)
	return discriminator.Discriminator, err
}

func (t BulkSpecSchema_Devices) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "JOBDEVICESFULL":
		return t.AsJobDeviceListTypedSchema()
	case "JOBDEVICESID":
		return t.AsJobCustomDeviceListTypedSchema()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t BulkSpecSchema_Devices) MarshalJSON() ([]byte, error) {
	b, err := t.Union.MarshalJSON()
	return b, err
}

func (t *BulkSpecSchema_Devices) UnmarshalJSON(b []byte) error {
	err := t.Union.UnmarshalJSON(b)
	return err
}

// AsExternalRef2DeviceRegistersDataSchema returns the union data inside the JobActionResultSchema_Data as a externalRef2.DeviceRegistersDataSchema
func (t JobActionResultSchema_Data) AsExternalRef2DeviceRegistersDataSchema() (externalRef2.DeviceRegistersDataSchema, error) {
	var body externalRef2.DeviceRegistersDataSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromExternalRef2DeviceRegistersDataSchema overwrites any union data inside the JobActionResultSchema_Data as the provided externalRef2.DeviceRegistersDataSchema
func (t *JobActionResultSchema_Data) FromExternalRef2DeviceRegistersDataSchema(v externalRef2.DeviceRegistersDataSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeExternalRef2DeviceRegistersDataSchema performs a merge with any union data inside the JobActionResultSchema_Data, using the provided externalRef2.DeviceRegistersDataSchema
func (t *JobActionResultSchema_Data) MergeExternalRef2DeviceRegistersDataSchema(v externalRef2.DeviceRegistersDataSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsExternalRef2DeviceProfileDataSchema returns the union data inside the JobActionResultSchema_Data as a externalRef2.DeviceProfileDataSchema
func (t JobActionResultSchema_Data) AsExternalRef2DeviceProfileDataSchema() (externalRef2.DeviceProfileDataSchema, error) {
	var body externalRef2.DeviceProfileDataSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromExternalRef2DeviceProfileDataSchema overwrites any union data inside the JobActionResultSchema_Data as the provided externalRef2.DeviceProfileDataSchema
func (t *JobActionResultSchema_Data) FromExternalRef2DeviceProfileDataSchema(v externalRef2.DeviceProfileDataSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeExternalRef2DeviceProfileDataSchema performs a merge with any union data inside the JobActionResultSchema_Data, using the provided externalRef2.DeviceProfileDataSchema
func (t *JobActionResultSchema_Data) MergeExternalRef2DeviceProfileDataSchema(v externalRef2.DeviceProfileDataSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

func (t JobActionResultSchema_Data) MarshalJSON() ([]byte, error) {
	b, err := t.Union.MarshalJSON()
	return b, err
}

func (t *JobActionResultSchema_Data) UnmarshalJSON(b []byte) error {
	err := t.Union.UnmarshalJSON(b)
	return err
}

// AsJobActionGetRegisterSchema returns the union data inside the JobActionSchema as a JobActionGetRegisterSchema
func (t JobActionSchema) AsJobActionGetRegisterSchema() (JobActionGetRegisterSchema, error) {
	var body JobActionGetRegisterSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionGetRegisterSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetRegisterSchema
func (t *JobActionSchema) FromJobActionGetRegisterSchema(v JobActionGetRegisterSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionGetRegisterSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetRegisterSchema
func (t *JobActionSchema) MergeJobActionGetRegisterSchema(v JobActionGetRegisterSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionGetPeriodicalProfileSchema returns the union data inside the JobActionSchema as a JobActionGetPeriodicalProfileSchema
func (t JobActionSchema) AsJobActionGetPeriodicalProfileSchema() (JobActionGetPeriodicalProfileSchema, error) {
	var body JobActionGetPeriodicalProfileSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionGetPeriodicalProfileSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetPeriodicalProfileSchema
func (t *JobActionSchema) FromJobActionGetPeriodicalProfileSchema(v JobActionGetPeriodicalProfileSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionGetPeriodicalProfileSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetPeriodicalProfileSchema
func (t *JobActionSchema) MergeJobActionGetPeriodicalProfileSchema(v JobActionGetPeriodicalProfileSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionGetIrregularProfileSchema returns the union data inside the JobActionSchema as a JobActionGetIrregularProfileSchema
func (t JobActionSchema) AsJobActionGetIrregularProfileSchema() (JobActionGetIrregularProfileSchema, error) {
	var body JobActionGetIrregularProfileSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionGetIrregularProfileSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetIrregularProfileSchema
func (t *JobActionSchema) FromJobActionGetIrregularProfileSchema(v JobActionGetIrregularProfileSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionGetIrregularProfileSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetIrregularProfileSchema
func (t *JobActionSchema) MergeJobActionGetIrregularProfileSchema(v JobActionGetIrregularProfileSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionGetEventsSchema returns the union data inside the JobActionSchema as a JobActionGetEventsSchema
func (t JobActionSchema) AsJobActionGetEventsSchema() (JobActionGetEventsSchema, error) {
	var body JobActionGetEventsSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionGetEventsSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetEventsSchema
func (t *JobActionSchema) FromJobActionGetEventsSchema(v JobActionGetEventsSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionGetEventsSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetEventsSchema
func (t *JobActionSchema) MergeJobActionGetEventsSchema(v JobActionGetEventsSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionGetClockSchema returns the union data inside the JobActionSchema as a JobActionGetClockSchema
func (t JobActionSchema) AsJobActionGetClockSchema() (JobActionGetClockSchema, error) {
	var body JobActionGetClockSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionGetClockSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetClockSchema
func (t *JobActionSchema) FromJobActionGetClockSchema(v JobActionGetClockSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionGetClockSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetClockSchema
func (t *JobActionSchema) MergeJobActionGetClockSchema(v JobActionGetClockSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionSyncClockSchema returns the union data inside the JobActionSchema as a JobActionSyncClockSchema
func (t JobActionSchema) AsJobActionSyncClockSchema() (JobActionSyncClockSchema, error) {
	var body JobActionSyncClockSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionSyncClockSchema overwrites any union data inside the JobActionSchema as the provided JobActionSyncClockSchema
func (t *JobActionSchema) FromJobActionSyncClockSchema(v JobActionSyncClockSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionSyncClockSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSyncClockSchema
func (t *JobActionSchema) MergeJobActionSyncClockSchema(v JobActionSyncClockSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionGetRelayStateSchema returns the union data inside the JobActionSchema as a JobActionGetRelayStateSchema
func (t JobActionSchema) AsJobActionGetRelayStateSchema() (JobActionGetRelayStateSchema, error) {
	var body JobActionGetRelayStateSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionGetRelayStateSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetRelayStateSchema
func (t *JobActionSchema) FromJobActionGetRelayStateSchema(v JobActionGetRelayStateSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionGetRelayStateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetRelayStateSchema
func (t *JobActionSchema) MergeJobActionGetRelayStateSchema(v JobActionGetRelayStateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionSetRelayStateSchema returns the union data inside the JobActionSchema as a JobActionSetRelayStateSchema
func (t JobActionSchema) AsJobActionSetRelayStateSchema() (JobActionSetRelayStateSchema, error) {
	var body JobActionSetRelayStateSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionSetRelayStateSchema overwrites any union data inside the JobActionSchema as the provided JobActionSetRelayStateSchema
func (t *JobActionSchema) FromJobActionSetRelayStateSchema(v JobActionSetRelayStateSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionSetRelayStateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSetRelayStateSchema
func (t *JobActionSchema) MergeJobActionSetRelayStateSchema(v JobActionSetRelayStateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionGetDisconnectorStateSchema returns the union data inside the JobActionSchema as a JobActionGetDisconnectorStateSchema
func (t JobActionSchema) AsJobActionGetDisconnectorStateSchema() (JobActionGetDisconnectorStateSchema, error) {
	var body JobActionGetDisconnectorStateSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionGetDisconnectorStateSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetDisconnectorStateSchema
func (t *JobActionSchema) FromJobActionGetDisconnectorStateSchema(v JobActionGetDisconnectorStateSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionGetDisconnectorStateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetDisconnectorStateSchema
func (t *JobActionSchema) MergeJobActionGetDisconnectorStateSchema(v JobActionGetDisconnectorStateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionSetDisconnectorStateSchema returns the union data inside the JobActionSchema as a JobActionSetDisconnectorStateSchema
func (t JobActionSchema) AsJobActionSetDisconnectorStateSchema() (JobActionSetDisconnectorStateSchema, error) {
	var body JobActionSetDisconnectorStateSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionSetDisconnectorStateSchema overwrites any union data inside the JobActionSchema as the provided JobActionSetDisconnectorStateSchema
func (t *JobActionSchema) FromJobActionSetDisconnectorStateSchema(v JobActionSetDisconnectorStateSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionSetDisconnectorStateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSetDisconnectorStateSchema
func (t *JobActionSchema) MergeJobActionSetDisconnectorStateSchema(v JobActionSetDisconnectorStateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionGetTouSchema returns the union data inside the JobActionSchema as a JobActionGetTouSchema
func (t JobActionSchema) AsJobActionGetTouSchema() (JobActionGetTouSchema, error) {
	var body JobActionGetTouSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionGetTouSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetTouSchema
func (t *JobActionSchema) FromJobActionGetTouSchema(v JobActionGetTouSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionGetTouSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetTouSchema
func (t *JobActionSchema) MergeJobActionGetTouSchema(v JobActionGetTouSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionSetTouSchema returns the union data inside the JobActionSchema as a JobActionSetTouSchema
func (t JobActionSchema) AsJobActionSetTouSchema() (JobActionSetTouSchema, error) {
	var body JobActionSetTouSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionSetTouSchema overwrites any union data inside the JobActionSchema as the provided JobActionSetTouSchema
func (t *JobActionSchema) FromJobActionSetTouSchema(v JobActionSetTouSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionSetTouSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSetTouSchema
func (t *JobActionSchema) MergeJobActionSetTouSchema(v JobActionSetTouSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionGetLimiterSchema returns the union data inside the JobActionSchema as a JobActionGetLimiterSchema
func (t JobActionSchema) AsJobActionGetLimiterSchema() (JobActionGetLimiterSchema, error) {
	var body JobActionGetLimiterSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionGetLimiterSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetLimiterSchema
func (t *JobActionSchema) FromJobActionGetLimiterSchema(v JobActionGetLimiterSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionGetLimiterSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetLimiterSchema
func (t *JobActionSchema) MergeJobActionGetLimiterSchema(v JobActionGetLimiterSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionSetLimiterSchema returns the union data inside the JobActionSchema as a JobActionSetLimiterSchema
func (t JobActionSchema) AsJobActionSetLimiterSchema() (JobActionSetLimiterSchema, error) {
	var body JobActionSetLimiterSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionSetLimiterSchema overwrites any union data inside the JobActionSchema as the provided JobActionSetLimiterSchema
func (t *JobActionSchema) FromJobActionSetLimiterSchema(v JobActionSetLimiterSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionSetLimiterSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSetLimiterSchema
func (t *JobActionSchema) MergeJobActionSetLimiterSchema(v JobActionSetLimiterSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionResetBillingPeriodSchema returns the union data inside the JobActionSchema as a JobActionResetBillingPeriodSchema
func (t JobActionSchema) AsJobActionResetBillingPeriodSchema() (JobActionResetBillingPeriodSchema, error) {
	var body JobActionResetBillingPeriodSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionResetBillingPeriodSchema overwrites any union data inside the JobActionSchema as the provided JobActionResetBillingPeriodSchema
func (t *JobActionSchema) FromJobActionResetBillingPeriodSchema(v JobActionResetBillingPeriodSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionResetBillingPeriodSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionResetBillingPeriodSchema
func (t *JobActionSchema) MergeJobActionResetBillingPeriodSchema(v JobActionResetBillingPeriodSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

// AsJobActionFwUpdateSchema returns the union data inside the JobActionSchema as a JobActionFwUpdateSchema
func (t JobActionSchema) AsJobActionFwUpdateSchema() (JobActionFwUpdateSchema, error) {
	var body JobActionFwUpdateSchema
	err := json.Unmarshal(t.Union, &body)
	return body, err
}

// FromJobActionFwUpdateSchema overwrites any union data inside the JobActionSchema as the provided JobActionFwUpdateSchema
func (t *JobActionSchema) FromJobActionFwUpdateSchema(v JobActionFwUpdateSchema) error {
	b, err := json.Marshal(v)
	t.Union = b
	return err
}

// MergeJobActionFwUpdateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionFwUpdateSchema
func (t *JobActionSchema) MergeJobActionFwUpdateSchema(v JobActionFwUpdateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.Union, b)
	t.Union = merged
	return err
}

func (t JobActionSchema) MarshalJSON() ([]byte, error) {
	b, err := t.Union.MarshalJSON()
	return b, err
}

func (t *JobActionSchema) UnmarshalJSON(b []byte) error {
	err := t.Union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9w8/W/jOHb/CqEW6EwrO187sx0DBZqxvXve8yS+ONkrOh1kaYm2uSORWpJK4h3kfy8e",
	"SUmUJdlWIs8B91MUiXx8X3x8X/Q3L+BxwhlhSnqDb54M1iTG+vEyUJSzyQieQyIDQRN44Q282zVBkxHi",
	"S6TWBGE9rv9/zPO9JRcxVt7AS1Maer6nNgnxBp5UgrKV9+x7H9Po636Qv/MFWqTR1z6y7+NUKrQgKGX0",
	"jxSWFFxKhKMIXSeE/WU8RwUZLTCZJySYa4qrGJn3SK2xQubLgkjATKIlFwgjmZCALmmAQkEfiECwglk7",
	"ETwhQlGi+Wj4ox//VZClN/D+5aTA9sRy/OQXvjAcn1KpLFLPvhdwIUiEd4nCGeLwsODf1ncqUSpJiBRH",
	"K8HTRI+0XGNpFOFFRLyBEimp4VpIHmhg6AopIBJThhUX8CLGSQLDBt+8X64/jsa/Tobj+U930+kOkkca",
	"HpB8u0lIaOn2HQBAdeP0YSoVj+uBPOeC2FzhGMiI7Aj4xBm5XnqDz3uFsnuJvdMbJn4BXmq90QjVytXR",
	"K6QFaIRmN4iRrf6Y7Q7OSCZ9mSYJFzDDgWKFHFM2JWyl1t7grEbENNynqnYTP/ueJEpRtjpEued2aCGd",
	"R7JYc/717mZaT//dzTQjxw4F8iVhIcKIcQWbz2j145owhNlGGw7Kcv0HXQ85I9smQdD9uv7se4L8kVJB",
	"Qm/w2dNGJNN+P9/UJSl+yYHwxe8kULmZUVilcszSuMnYALlSjwKKsdm8nu8Rlsbe4POpf+af+xf+D8UK",
	"lCmyIsLzvacejOo5ACUgfOvw4I+UpCTUdisRPCBSUrYCBaIyW5aCOZXAXoXwUhGBMENYKRInCi0xjSTg",
	"4wINUiEIU9EGLQhlqwwyCSsDeZxERG19WGOJFoQwFGAWkCiq+UyeEmB/HxhrqXzAguGYaAr/dje+G488",
	"37u5u7qaXP3s+d7w+tNsOr7Vb4eXV8PxdKqfx/8zm9yMR96XkkTamf5cqQzH+hVDv6SMyjUJL1W9gBWN",
	"iVFVVWFCjMVXEiLscqustCFWpAcgDjHTUmHY/C/BpF5XXoeLSuUhNqWyT7Y3oQVVt8/y43PI45izJtGa",
	"r2hJSRRKJNdYWFrBl7CbuvYQV0rQRarIXkJ4QhhO6D38XRN5b2xG9ucyh1PYwf0GN3fFaq2Sg9tOzvz0",
	"eJeA5Are4Cg67BCsYS2cfWUewcr3y8f7VK9iPIInGoMFO9OnTv68ZcO2qdoCVCXqi3/wjjUy1QcH7AmE",
	"0ZKK+BELggz4folHPxM1jHjw9ag8WhF1H8Aqr+VRAagjHq2I0m800ApnRlQGnDESKC5gr5Kjcyl0VryH",
	"3U+6YFkN1I75566gz4uqmo0fgDVH5yB5yEK713LNQuqQUwZihTMTIcgqjbCYCb6k0fG1jGYL3idmxS7Y",
	"VQXaIecwQzl8ZOFX+DilMVVEHJ19kVmnC6ZloDrejhYsysKVCqtmRFAe0gBHR9a5BAsc36ul4HFjFCCU",
	"cdBs7GPFi0Ks8A4/rOJ32aUUr18Iwqgulslll+Q87HIb1UDtch+hAn7jProhKyq/x0YSdqEu+JbD6pRb",
	"GdQaHkV48318AgFLdecMuOA6NjsadMPxf8vTo3NK8bQLDgGYjjkDxqTHl71UEqQgeizzx0mBVmzXJYqo",
	"VDpNYsI1gLsgTvoBXTJE4kRtEBYCbxCViHGFHnBEQx9hhSKCAQLLMcsSaIkgkjBlUmsZeAgVcuBZdkli",
	"sJwiJAJidrUmGz0uJEvKilGAqbGlVJH48BRwERvW5uo0WSWG3RBJ1EcaRZStzFl2VOUCNqn7hVnPmujX",
	"alotzI7UTsM2uQ4D35r9/jYT08jRuzLhAQ8b8rRCz9sqh6CJ+y/ooEwD0KFlGvn6ywOOUgIflEgJwixE",
	"DzQg6IEICQcwQv+Ofrv+62+o52hjkaYpoEUbR/ftvLur+d1sdn1zOx5tAbCbocgPLzYmYtFpzGz++Obm",
	"+gZmznlMEBGCC4nW+IEgHui8X4jCFDyAzHWweaJKTUhDu7q+vZ/dXA/H83kFHyAIENJEuXQU2U/v+q+e",
	"7zkkeb6nEfR8rwTaURenYoEV3ik3GFBXyzqsQlBJ92g+2j8A2n00xYDMn5AjrPCBlYQXLGM9WXeRLx1k",
	"m/Q+sGzdmW5ql13Ncm9ei9JMk4d2QFlmr+ffBkZDwNoGRCkb0Gaim606eN58w4IXTazz9A5f9TWTd6Sf",
	"2iDwahgl163Nyi+YVYnh26z3wpmNnsTBELbSzNroHCKC47gq8ihZRHnULKI8MIs4/z45Htldjkd2n+OR",
	"B+V45t8tRJXdhqjyOCGq3Beizo8fospuQlTZbYgqDwtRt4/QI7Fow4JuSkUOpK4YtWHBWnBG/yTVmtF2",
	"10yTMzi1sXygx/dsg4UN6U0pul0A7S7cIoze1eVTCQVfgku5qyvvRNIMWeI0Ut5gu2uqCIC2PnzZ16yS",
	"g8/41uCo1zCrQixOksj22cwEVzzgUesSuBus3F9WAbrtbvq8g/iDLXlTv1s2BlFmktTwbEM4o0ItlGZ3",
	"wX5YQqikURMDvUahzNzLI/YMkCdFBMNRU09gki4iGjjtgC5b9rZs7I8Rf+EL0wEGZvJPzkhzo8mfTlta",
	"CyzqY8+SdtQwukHRDzdEBiKiIWGKLikRZWPko4jzr7pjJLNVlGWTTHZcbNpZrNa2qmMr9RL7NBnVWqfJ",
	"qDvbtNsqGY5Pwn2dxK7C7W0JPljtm3sDJ2ETPWMhuBjykOzqASynEn/niyKFdjX+DfXQFTfZOD/vkz4w",
	"I1iT0Xsj37bJ6TnY/HR5eznNEnmARMDTKLR5PCdZHqYEdg9GS6xwZFYtp/aALiedpwHXpvEM5/f3jR+z",
	"ZbzaxXp413gRlxj6n3CcmAqpbbKU3uDzmXbElgTiYqG8wSkMTKgg8hLwOj89/7F3dt67OLs9vxi8+zB4",
	"9+F/PR/cwlEqsMHg4v3pqe8lgnJB1UaDEESJzQgcfW/w/vS5prXNru/sdYvKNqtZGi+I0MUXOwvkawWe",
	"q2RCBDA3TlnWoJsyaqsqdgVEJfp89qXv2smc/5Spi3NDmPFxP3zY7fDuPY4Lljo0ntZRGOqAiDIkScBZ",
	"CHtryYWty2ebY0mFVHl3rKN8rhZRpt7/4FLxn+9/ANnkhJzWEeLIe3/nJjDbTugfXLAvqYvDDqM51SUt",
	"/mAcsHW6cuZUhb+bBT+elzhw9q6OBYXy7hNWNrKy/yP+SERRZTHWsniZzdtGdkvr9snK3VgOqu9bKZYG",
	"kinWXgZ++LAHq+f608e01sLxc3gbuoPQK/vQdVt+x23oFubeLvRs3HYTeunsrPSgZ1+P04KeC6R9B7p7",
	"S8AKp75OuceN2XZHnv2W/ev2Xkk2yXUYCm/hxU3jxhGSu7wkWS7aSV1yBW3ZVVj0bdZL2jMIRmRV/xcU",
	"6ksl4+dGuvKTqFVfvuWwndMxgw/rym+yHA2N+bY6WOcBtwxxwS8JQwq80ZU5119hG5tm2ybqW9VG56+M",
	"5+K+WXAeEcx09qvMrufD0mFYWynjC1nsdRlfrQkV5uCR5jj6SnQXivWr9ZU0BDYkG+70ArhD9FsDwQwI",
	"MNP3vJbm3pch3EeWXN+6Zz6ypPloQRkWGx9xgYBEozBl2YBdW/FepqkZKX0nqHaG9GiccONHJRhCVG9F",
	"1Tpd9AMenwSbheAywgt5siayd97DCc2TGydW8if5ElqLXpB9KaVay8YvouxrN1mqEVZ46kBrUPzSgjV6",
	"/+2lbQQNbIDI+TZIJslL+wZ2wJ2tOSNTysgRYM+JoDj6xJ/w0YCPqCCBKqqOX1poVx35LQ7lBKaiiDKC",
	"3sQ8JPFbJ0lZd53IWqP61J0GVkRa22mMPdc3E86je9qQGNHIIRiCJqMDo15dPtATX1uDMED8jPoC1/YH",
	"xl4FaCG9UM9Dk5kp/wAoV3xoopAg1kmQSFJwJFGy3kjdNayl/kjVmqdK30HlrBeSGCx7wNmS2qDpDemv",
	"+kgmhIRgjRMM8cdb2zxoRq7yAMu4wwA+2phDxngEk1lP8Z5F0dWJsnatuWxwMCYzhMNQQLzGTSgEY/VR",
	"VKNpNbolGgDDlx06WyhZJcp6/+7dxbt94b0t9AHd90Zcr68ausB8wzNLYTfq6Bi7FspYErFT6Ui144cR",
	"QM1Yqz0D/cK280kUbhiOaeCosaNXwRqzFZHogWKdn7E6usNO2VGzf5TcQ6zwP2zxo20jVwFj/oQ70mUN",
	"KtfknHV+SYqv1W3X+Wih1rfD2clktkfb/kntlgqS10oYQLzARh1Yd62PRSHCyCLsYiqK8KboE56Mh/fv",
	"z0/fvb8/P8vqAZPxEOl3vfMz9GYyHvben52d/uijX0fjv7+F6EavnYEYTT/N7+dX2Wz4F8k1F6qnxVs7",
	"fFoeHvEVnJX1E+bD20/ZaHiuDJhO5uenp9kQ819l0OXVfHI/PDvPhsH/aHh2Xhn46W+3t9kgeK4OuB59",
	"vJvnQ3i4SKU7yCmOuNz1fM9yKnuawhNQ5PmewdrzvQxPz/dgdfij16utqbwoAtqrLGB4ehAX7VcV0Ait",
	"IrnC+ChXGEdV0ITBgQXRrPm9D6rWRvTZEDdhQhlVFCuSuVZuIWKx0foJJ598pCpYm2YTZX1jNM7++8to",
	"OvyP0hJ9NM9OWWuL4ET+LxSnkaLgEmYFYe5cEQHvMOMAgMwoh2f0ZjK/PgF6Ly5OP7xFS4FjnRCdqCzS",
	"1z/Us+QCPWBBeSpLOzFDTPpIpsEafEmNMBfICN3BOIgoYepEEgEcehn+w+v5+NP9328uZ7PxTUaIfoke",
	"BU4SImpR1zjV4d0xers3FmAm1ziKSrjZUXXYocc1EQQxjrhaE2GuCRRqXfAcROlnv6qUI+Oi0vt4ACZ6",
	"UC2bnFsUl7PZdDK8/DgdZ8ALtHLEbVrTwlpEBJb8N43fMo30ahGVijBgcHl7FL9h1WCDgFid5HZUoTAy",
	"vvfJ/Cnj2t747LzR8LHcdndw5pyyVaRDLUVZCptpAYDAbFXvvpYdE1nUDvff19VQ29ygNZnCV6Wr9vPr",
	"V72Ik8Vq5z20XKCFWLLbfJkMbN70Ff1bu/D+mTAiaKCRLZVgnqvJ+lcypANeaFU6Gi8aN1WnvHDuH7XJ",
	"qO3ZkYYzR2aHoxvFHceaGEJ/q7tH75R7twxCFk5UQ4aU0QZTA1+ab+vv7rqy/LLgc3q+dGMHsvtXL5N1",
	"dqm8UdhgOKXCcdJcNdOfXQ+0jQE+jOWNrLYW/DvZqeduRSZfJrPMUmWyO7KRqlGw1xqpRg63dylMcU4H",
	"JVTlrQwQY5AnQ3ydVmffGn6ew37NtM/UAg81IkV1d1+DRwNc3XVShZsrehWsA6goeVUrtPsXccaEPF1E",
	"zpbdVcSt2Rjwito2cnD7sEkbkxjTSC+55P9d1Cz7AdfFCfNboUP9Hk3xQiJFMHxJBcxaK5XIwcnJ4+Nj",
	"vzz5hLKQPPUI669VHJk22oAwqRlmwX6cT3tn/dMKNFBZyVMRkD4XqxM7UZ5k43WntYpI8RN2l7OJDlkj",
	"83u0tqnR870HIqQRy2nfTrUbwxt4F/3T/gWoIlZr6Q1YGkXP/x8AAP//fFIvNgRYAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../device/device.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../driver/driver.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../driver/driverdata/driverdata.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
