// Package job provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package job

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/cybroslabs/hes-2-apis/openapi/openhes/attribute"
	externalRef0 "github.com/cybroslabs/hes-2-apis/openapi/openhes/driver/driverdata"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ActionTypeSchema.
const (
	FWUPDATE             ActionTypeSchema = "FW_UPDATE"
	GETCLOCK             ActionTypeSchema = "GET_CLOCK"
	GETDISCONNECTORSTATE ActionTypeSchema = "GET_DISCONNECTOR_STATE"
	GETEVENTS            ActionTypeSchema = "GET_EVENTS"
	GETIRREGULARPROFILE  ActionTypeSchema = "GET_IRREGULAR_PROFILE"
	GETLIMITER           ActionTypeSchema = "GET_LIMITER"
	GETPERIODICALPROFILE ActionTypeSchema = "GET_PERIODICAL_PROFILE"
	GETREGISTER          ActionTypeSchema = "GET_REGISTER"
	GETRELAYSTATE        ActionTypeSchema = "GET_RELAY_STATE"
	GETTOU               ActionTypeSchema = "GET_TOU"
	RESETBILLINGPERIOD   ActionTypeSchema = "RESET_BILLING_PERIOD"
	SETDISCONNECTORSTATE ActionTypeSchema = "SET_DISCONNECTOR_STATE"
	SETLIMITER           ActionTypeSchema = "SET_LIMITER"
	SETRELAYSTATE        ActionTypeSchema = "SET_RELAY_STATE"
	SETTOU               ActionTypeSchema = "SET_TOU"
	SYNCCLOCK            ActionTypeSchema = "SYNC_CLOCK"
)

// Defines values for BulkStatusEnumSchema.
const (
	BulkStatusEnumSchemaCANCELLED BulkStatusEnumSchema = 3
	BulkStatusEnumSchemaCOMPLETED BulkStatusEnumSchema = 2
	BulkStatusEnumSchemaEXPIRED   BulkStatusEnumSchema = 4
	BulkStatusEnumSchemaQUEUED    BulkStatusEnumSchema = 0
	BulkStatusEnumSchemaRUNNING   BulkStatusEnumSchema = 1
)

// Defines values for JobActionResultSchemaCode.
const (
	JobActionResultSchemaCodeERROR        JobActionResultSchemaCode = "ERROR"
	JobActionResultSchemaCodeNOTPROCESSED JobActionResultSchemaCode = "NOT_PROCESSED"
	JobActionResultSchemaCodeOK           JobActionResultSchemaCode = "OK"
	JobActionResultSchemaCodeUNSUPPORTED  JobActionResultSchemaCode = "UNSUPPORTED"
)

// Defines values for JobErrorCodeSchema.
const (
	JobErrorCodeSchemaERROR JobErrorCodeSchema = "ERROR"
	JobErrorCodeSchemaFATAL JobErrorCodeSchema = "FATAL"
	JobErrorCodeSchemaNONE  JobErrorCodeSchema = "NONE"
)

// Defines values for JobStatusCodeEnumSchema.
const (
	JobStatusCodeEnumSchemaCANCELLED JobStatusCodeEnumSchema = 3
	JobStatusCodeEnumSchemaCOMPLETED JobStatusCodeEnumSchema = 2
	JobStatusCodeEnumSchemaEXPIRED   JobStatusCodeEnumSchema = 4
	JobStatusCodeEnumSchemaQUEUED    JobStatusCodeEnumSchema = 0
	JobStatusCodeEnumSchemaRUNNING   JobStatusCodeEnumSchema = 1
)

// ActionID The ID of the action.
type ActionID = openapi_types.UUID

// ActionTypeSchema The type of action.
//   - `GET_REGISTER` - The action is to get a billing value, for example, instantaneous values.
//   - `GET_PERIODICAL_PROFILE` - The action is to get a periodical profile, for example, load-profile.
//   - `GET_IRREGULAR_PROFILE` - The action is to get a non-periodical profile, for, daily profile or monthly billing registers.
//   - `GET_EVENTS` - The action is to get an event log.
//   - `GET_CLOCK` - The action is to get the clock.
//   - `SYNC_CLOCK` - The action is to synchronize the clock. The action synchronizes the clock in the device. If the force attribute is set, it forcefully sets the clock.
//   - `GET_RELAY_STATE` - The action is to get the relay state.
//   - `SET_RELAY_STATE` - The action is to set the relay state.
//   - `GET_DISCONNECTOR_STATE` - The action is to get the disconnector state.
//   - `SET_DISCONNECTOR_STATE` - The action is to set the disconnector state.
//   - `GET_TOU` - The action is to get the time-of-use table.
//   - `SET_TOU` - The action is to set the time-of-use table.
//   - `GET_LIMITER` - The action is to get the limiter settings.
//   - `SET_LIMITER` - The action is to set the limiter settings.
//   - `RESET_BILLING_PERIOD` - The action is to reset the billing period.
//   - `FW_UPDATE` - The action is to start a firmware update.
type ActionTypeSchema string

// AttributesSchema Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
type AttributesSchema = attribute.Attributes

// BulkID The ID of the job bulk. The ID must be unique across all OpenHES components.
type BulkID = openapi_types.UUID

// BulkSpecSchema Schema that describes jobs for a specific driver type.
type BulkSpecSchema struct {
	// Actions A list of actions to be processed. An empty array is not valid, at least one action must be present. The actions are processed in the same order as they are defined in the list.
	Actions JobActionListSchema `json:"actions"`

	// CorrelationID The correlation ID of the bulk. The correlation ID is used to group bulks.
	CorrelationID *string `json:"correlationID"`

	// Devices List of devices to be queued.
	Devices JobDeviceListSchema `json:"devices"`

	// DriverType The driver type related to the job. The type must be one of the supported driver types.
	DriverType string `json:"driverType"`

	// Id The ID of the job bulk. The ID must be unique across all OpenHES components.
	Id BulkID `json:"id"`

	// Settings Schema that describes job settings.
	Settings *JobSettingsSchema `json:"settings,omitempty"`

	// WebhookURL The URL of the webhook to send a notification when any job in the bulk is done.
	WebhookURL *string `json:"webhookURL"`
}

// BulkStatusEnumSchema The status of a bulk.
type BulkStatusEnumSchema int

// BulkStatusSchema Schema that describes the bulk status.
type BulkStatusSchema struct {
	// FinishedAt The time when the bulk has been marked as completed.
	FinishedAt *time.Time `json:"finishedAt"`

	// StartedAt The time when the bulk has been queued for processing.
	StartedAt *time.Time `json:"startedAt"`

	// Status The status of a bulk.
	Status BulkStatusEnumSchema `json:"status"`
}

// ConnectionTypePhoneLineSchema Schema that describes the phone line (modem) connection.
type ConnectionTypePhoneLineSchema struct {
	// Number The phone number of the device.
	Number string `json:"number"`

	// PoolId The modem pool ID.
	PoolId    openapi_types.UUID `json:"pool_id"`
	TypeModem int                `json:"type_modem"`
}

// ConnectionTypeSchema defines model for ConnectionTypeSchema.
type ConnectionTypeSchema struct {
	union json.RawMessage
}

// ConnectionTypeSerialMoxaSchema Schema that describes the MOXA connection.
type ConnectionTypeSerialMoxaSchema struct {
	// CommandPort The port number of the device.
	CommandPort int `json:"commandPort"`

	// DataPort The port number of the device.
	DataPort int `json:"dataPort"`

	// Host The IP address or the hostname of the device.
	Host     string `json:"host"`
	TypeMoxa int    `json:"type_moxa"`
}

// ConnectionTypeTcpIpSchema Schema that describes the TCP/IP connection.
type ConnectionTypeTcpIpSchema struct {
	// Host The IP address or the hostname of the device.
	Host string `json:"host"`

	// Port The port number of the device.
	Port    int `json:"port"`
	TypeTcp int `json:"type_tcp"`
}

// JobActionCommonSchema Common fields shared for all actions.
type JobActionCommonSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id ActionID `json:"id"`
}

// JobActionFwUpdateSchema defines model for JobActionFwUpdateSchema.
type JobActionFwUpdateSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id           ActionID `json:"id"`
	TypeFwUpdate int      `json:"type_fw_update"`
}

// JobActionGetClockSchema defines model for JobActionGetClockSchema.
type JobActionGetClockSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id           ActionID `json:"id"`
	TypeGetClock int      `json:"type_get_clock"`
}

// JobActionGetDisconnectorStateSchema defines model for JobActionGetDisconnectorStateSchema.
type JobActionGetDisconnectorStateSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                       ActionID `json:"id"`
	TypeGetDisconnectorState int      `json:"type_get_disconnector_state"`
}

// JobActionGetEventsSchema defines model for JobActionGetEventsSchema.
type JobActionGetEventsSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id            ActionID `json:"id"`
	TypeGetEvents int      `json:"type_get_events"`
}

// JobActionGetIrregularProfileSchema defines model for JobActionGetIrregularProfileSchema.
type JobActionGetIrregularProfileSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                      ActionID `json:"id"`
	TypeGetIrregularProfile int      `json:"type_get_irregular_profile"`
}

// JobActionGetLimiterSchema defines model for JobActionGetLimiterSchema.
type JobActionGetLimiterSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id             ActionID `json:"id"`
	TypeGetLimiter int      `json:"type_get_limiter"`
}

// JobActionGetPeriodicalProfileSchema defines model for JobActionGetPeriodicalProfileSchema.
type JobActionGetPeriodicalProfileSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id ActionID `json:"id"`

	// ParamTfrom The start time of the profile data.
	ParamTfrom *time.Time `json:"param_tfrom,omitempty"`

	// ParamTto The end time of the profile data.
	ParamTto                 *time.Time `json:"param_tto,omitempty"`
	TypeGetPeriodicalProfile int        `json:"type_get_periodical_profile"`
}

// JobActionGetRegisterSchema defines model for JobActionGetRegisterSchema.
type JobActionGetRegisterSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id              ActionID `json:"id"`
	TypeGetRegister int      `json:"type_get_register"`
}

// JobActionGetRelayStateSchema defines model for JobActionGetRelayStateSchema.
type JobActionGetRelayStateSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                ActionID `json:"id"`
	TypeGetRelayState int      `json:"type_get_relay_state"`
}

// JobActionGetTouSchema defines model for JobActionGetTouSchema.
type JobActionGetTouSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id         ActionID `json:"id"`
	TypeGetTou int      `json:"type_get_tou"`
}

// JobActionListSchema A list of actions to be processed. An empty array is not valid, at least one action must be present. The actions are processed in the same order as they are defined in the list.
type JobActionListSchema = []JobActionSchema

// JobActionResetBillingPeriodSchema defines model for JobActionResetBillingPeriodSchema.
type JobActionResetBillingPeriodSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                     ActionID `json:"id"`
	TypeResetBillingPeriod int      `json:"type_reset_billing_period"`
}

// JobActionResultSchema defines model for JobActionResultSchema.
type JobActionResultSchema struct {
	// Code The result of the action. If the action is successful, the value is true and vice versa.
	//   * `OK` - The action has been successfully processed.
	//   * `UNSUPPORTED` - The action is not supported by the driver.
	//   * `ERROR` - Some errors have occurred during the processing of the action.
	//   * `NOT_PROCESSED` - The action has not been processed.
	Code JobActionResultSchemaCode `json:"code"`

	// Data The result data of the action.
	Data JobActionResultSchema_Data `json:"data"`

	// Id The ID of the action.
	Id ActionID `json:"id"`
}

// JobActionResultSchemaCode The result of the action. If the action is successful, the value is true and vice versa.
//   - `OK` - The action has been successfully processed.
//   - `UNSUPPORTED` - The action is not supported by the driver.
//   - `ERROR` - Some errors have occurred during the processing of the action.
//   - `NOT_PROCESSED` - The action has not been processed.
type JobActionResultSchemaCode string

// JobActionResultSchema_Data The result data of the action.
type JobActionResultSchema_Data struct {
	union json.RawMessage
}

// JobActionSchema Schema that describes actions.
type JobActionSchema struct {
	union json.RawMessage
}

// JobActionSetDisconnectorStateSchema defines model for JobActionSetDisconnectorStateSchema.
type JobActionSetDisconnectorStateSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                       ActionID `json:"id"`
	TypeSetDisconnectorState int      `json:"type_set_disconnector_state"`
}

// JobActionSetLimiterSchema defines model for JobActionSetLimiterSchema.
type JobActionSetLimiterSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id             ActionID `json:"id"`
	TypeSetLimiter int      `json:"type_set_limiter"`
}

// JobActionSetRelayStateSchema defines model for JobActionSetRelayStateSchema.
type JobActionSetRelayStateSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id                ActionID `json:"id"`
	TypeSetRelayState int      `json:"type_set_relay_state"`
}

// JobActionSetTouSchema defines model for JobActionSetTouSchema.
type JobActionSetTouSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id         ActionID `json:"id"`
	TypeSetTou int      `json:"type_set_tou"`
}

// JobActionSyncClockSchema defines model for JobActionSyncClockSchema.
type JobActionSyncClockSchema struct {
	// Attributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes AttributesSchema `json:"attributes"`

	// Id The ID of the action.
	Id            ActionID `json:"id"`
	TypeSyncClock int      `json:"type_sync_clock"`
}

// JobDeviceListSchema List of devices to be queued.
type JobDeviceListSchema = []JobDeviceSchema

// JobDeviceSchema defines model for JobDeviceSchema.
type JobDeviceSchema struct {
	ConnectionInfo ConnectionTypeSchema `json:"connectionInfo"`

	// DeviceAttributes Schema that describes a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	DeviceAttributes AttributesSchema `json:"deviceAttributes"`

	// ExternalID The public ID of the device.
	ExternalID *string `json:"externalID"`

	// Id The ID of the job. The ID must be unique across all OpenHES components.
	Id JobID `json:"id"`

	// Timezone The timezone of the device.
	Timezone *string `json:"timezone"`
}

// JobErrorCodeSchema The result of the job.
//   - `NONE` - No error, the job has been successfully processed.
//   - `ERROR` - Some error(s) have occurred during the processing of the job.
//   - `FATAL` - The job could not be processed due to a fatal error.
type JobErrorCodeSchema string

// JobID The ID of the job. The ID must be unique across all OpenHES components.
type JobID = openapi_types.UUID

// JobSettingsSchema Schema that describes job settings.
type JobSettingsSchema struct {
	// Attempts The number of attempts to process the job.
	Attempts *int32 `json:"attempts,omitempty"`

	// DeferStart The delay in seconds before starting the first attempt of the job.
	DeferStart *int64 `json:"deferStart,omitempty"`

	// ExpiresAt The time when the job expires.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// MaxDuration The maximum duration in seconds to process the job.
	MaxDuration *int64 `json:"maxDuration,omitempty"`

	// Priority The priority of the job.
	Priority *int32 `json:"priority,omitempty"`

	// RetryDelay The delay in seconds before retrying the job.
	RetryDelay *int64 `json:"retryDelay,omitempty"`
}

// JobStatusCodeEnumSchema The status of the job.
type JobStatusCodeEnumSchema int

// JobStatusSchema Schema that describes the status of a job.
type JobStatusSchema struct {
	// Code The result of the job.
	//   * `NONE` - No error, the job has been successfully processed.
	//   * `ERROR` - Some error(s) have occurred during the processing of the job.
	//   * `FATAL` - The job could not be processed due to a fatal error.
	Code JobErrorCodeSchema `json:"code"`

	// FinishedAt The time when the driver finished processing the job.
	FinishedAt *time.Time `json:"finishedAt"`

	// Results The results of the actions. If an action has not been processed, the result is not present.
	Results *[]JobActionResultSchema `json:"results"`

	// StartedAt The time when the driver started processing the job.
	StartedAt *time.Time `json:"startedAt"`

	// Status The status of the job.
	Status JobStatusCodeEnumSchema `json:"status"`
}

// AsConnectionTypeTcpIpSchema returns the union data inside the ConnectionTypeSchema as a ConnectionTypeTcpIpSchema
func (t ConnectionTypeSchema) AsConnectionTypeTcpIpSchema() (ConnectionTypeTcpIpSchema, error) {
	var body ConnectionTypeTcpIpSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConnectionTypeTcpIpSchema overwrites any union data inside the ConnectionTypeSchema as the provided ConnectionTypeTcpIpSchema
func (t *ConnectionTypeSchema) FromConnectionTypeTcpIpSchema(v ConnectionTypeTcpIpSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConnectionTypeTcpIpSchema performs a merge with any union data inside the ConnectionTypeSchema, using the provided ConnectionTypeTcpIpSchema
func (t *ConnectionTypeSchema) MergeConnectionTypeTcpIpSchema(v ConnectionTypeTcpIpSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConnectionTypePhoneLineSchema returns the union data inside the ConnectionTypeSchema as a ConnectionTypePhoneLineSchema
func (t ConnectionTypeSchema) AsConnectionTypePhoneLineSchema() (ConnectionTypePhoneLineSchema, error) {
	var body ConnectionTypePhoneLineSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConnectionTypePhoneLineSchema overwrites any union data inside the ConnectionTypeSchema as the provided ConnectionTypePhoneLineSchema
func (t *ConnectionTypeSchema) FromConnectionTypePhoneLineSchema(v ConnectionTypePhoneLineSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConnectionTypePhoneLineSchema performs a merge with any union data inside the ConnectionTypeSchema, using the provided ConnectionTypePhoneLineSchema
func (t *ConnectionTypeSchema) MergeConnectionTypePhoneLineSchema(v ConnectionTypePhoneLineSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConnectionTypeSerialMoxaSchema returns the union data inside the ConnectionTypeSchema as a ConnectionTypeSerialMoxaSchema
func (t ConnectionTypeSchema) AsConnectionTypeSerialMoxaSchema() (ConnectionTypeSerialMoxaSchema, error) {
	var body ConnectionTypeSerialMoxaSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConnectionTypeSerialMoxaSchema overwrites any union data inside the ConnectionTypeSchema as the provided ConnectionTypeSerialMoxaSchema
func (t *ConnectionTypeSchema) FromConnectionTypeSerialMoxaSchema(v ConnectionTypeSerialMoxaSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConnectionTypeSerialMoxaSchema performs a merge with any union data inside the ConnectionTypeSchema, using the provided ConnectionTypeSerialMoxaSchema
func (t *ConnectionTypeSchema) MergeConnectionTypeSerialMoxaSchema(v ConnectionTypeSerialMoxaSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ConnectionTypeSchema) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ConnectionTypeSchema) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsExternalRef0DeviceRegistersDataSchema returns the union data inside the JobActionResultSchema_Data as a externalRef0.DeviceRegistersDataSchema
func (t JobActionResultSchema_Data) AsExternalRef0DeviceRegistersDataSchema() (externalRef0.DeviceRegistersDataSchema, error) {
	var body externalRef0.DeviceRegistersDataSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExternalRef0DeviceRegistersDataSchema overwrites any union data inside the JobActionResultSchema_Data as the provided externalRef0.DeviceRegistersDataSchema
func (t *JobActionResultSchema_Data) FromExternalRef0DeviceRegistersDataSchema(v externalRef0.DeviceRegistersDataSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExternalRef0DeviceRegistersDataSchema performs a merge with any union data inside the JobActionResultSchema_Data, using the provided externalRef0.DeviceRegistersDataSchema
func (t *JobActionResultSchema_Data) MergeExternalRef0DeviceRegistersDataSchema(v externalRef0.DeviceRegistersDataSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsExternalRef0DeviceProfileDataSchema returns the union data inside the JobActionResultSchema_Data as a externalRef0.DeviceProfileDataSchema
func (t JobActionResultSchema_Data) AsExternalRef0DeviceProfileDataSchema() (externalRef0.DeviceProfileDataSchema, error) {
	var body externalRef0.DeviceProfileDataSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExternalRef0DeviceProfileDataSchema overwrites any union data inside the JobActionResultSchema_Data as the provided externalRef0.DeviceProfileDataSchema
func (t *JobActionResultSchema_Data) FromExternalRef0DeviceProfileDataSchema(v externalRef0.DeviceProfileDataSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExternalRef0DeviceProfileDataSchema performs a merge with any union data inside the JobActionResultSchema_Data, using the provided externalRef0.DeviceProfileDataSchema
func (t *JobActionResultSchema_Data) MergeExternalRef0DeviceProfileDataSchema(v externalRef0.DeviceProfileDataSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t JobActionResultSchema_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *JobActionResultSchema_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsJobActionGetRegisterSchema returns the union data inside the JobActionSchema as a JobActionGetRegisterSchema
func (t JobActionSchema) AsJobActionGetRegisterSchema() (JobActionGetRegisterSchema, error) {
	var body JobActionGetRegisterSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetRegisterSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetRegisterSchema
func (t *JobActionSchema) FromJobActionGetRegisterSchema(v JobActionGetRegisterSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetRegisterSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetRegisterSchema
func (t *JobActionSchema) MergeJobActionGetRegisterSchema(v JobActionGetRegisterSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetPeriodicalProfileSchema returns the union data inside the JobActionSchema as a JobActionGetPeriodicalProfileSchema
func (t JobActionSchema) AsJobActionGetPeriodicalProfileSchema() (JobActionGetPeriodicalProfileSchema, error) {
	var body JobActionGetPeriodicalProfileSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetPeriodicalProfileSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetPeriodicalProfileSchema
func (t *JobActionSchema) FromJobActionGetPeriodicalProfileSchema(v JobActionGetPeriodicalProfileSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetPeriodicalProfileSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetPeriodicalProfileSchema
func (t *JobActionSchema) MergeJobActionGetPeriodicalProfileSchema(v JobActionGetPeriodicalProfileSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetIrregularProfileSchema returns the union data inside the JobActionSchema as a JobActionGetIrregularProfileSchema
func (t JobActionSchema) AsJobActionGetIrregularProfileSchema() (JobActionGetIrregularProfileSchema, error) {
	var body JobActionGetIrregularProfileSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetIrregularProfileSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetIrregularProfileSchema
func (t *JobActionSchema) FromJobActionGetIrregularProfileSchema(v JobActionGetIrregularProfileSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetIrregularProfileSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetIrregularProfileSchema
func (t *JobActionSchema) MergeJobActionGetIrregularProfileSchema(v JobActionGetIrregularProfileSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetEventsSchema returns the union data inside the JobActionSchema as a JobActionGetEventsSchema
func (t JobActionSchema) AsJobActionGetEventsSchema() (JobActionGetEventsSchema, error) {
	var body JobActionGetEventsSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetEventsSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetEventsSchema
func (t *JobActionSchema) FromJobActionGetEventsSchema(v JobActionGetEventsSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetEventsSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetEventsSchema
func (t *JobActionSchema) MergeJobActionGetEventsSchema(v JobActionGetEventsSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetClockSchema returns the union data inside the JobActionSchema as a JobActionGetClockSchema
func (t JobActionSchema) AsJobActionGetClockSchema() (JobActionGetClockSchema, error) {
	var body JobActionGetClockSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetClockSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetClockSchema
func (t *JobActionSchema) FromJobActionGetClockSchema(v JobActionGetClockSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetClockSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetClockSchema
func (t *JobActionSchema) MergeJobActionGetClockSchema(v JobActionGetClockSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionSyncClockSchema returns the union data inside the JobActionSchema as a JobActionSyncClockSchema
func (t JobActionSchema) AsJobActionSyncClockSchema() (JobActionSyncClockSchema, error) {
	var body JobActionSyncClockSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionSyncClockSchema overwrites any union data inside the JobActionSchema as the provided JobActionSyncClockSchema
func (t *JobActionSchema) FromJobActionSyncClockSchema(v JobActionSyncClockSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionSyncClockSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSyncClockSchema
func (t *JobActionSchema) MergeJobActionSyncClockSchema(v JobActionSyncClockSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetRelayStateSchema returns the union data inside the JobActionSchema as a JobActionGetRelayStateSchema
func (t JobActionSchema) AsJobActionGetRelayStateSchema() (JobActionGetRelayStateSchema, error) {
	var body JobActionGetRelayStateSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetRelayStateSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetRelayStateSchema
func (t *JobActionSchema) FromJobActionGetRelayStateSchema(v JobActionGetRelayStateSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetRelayStateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetRelayStateSchema
func (t *JobActionSchema) MergeJobActionGetRelayStateSchema(v JobActionGetRelayStateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionSetRelayStateSchema returns the union data inside the JobActionSchema as a JobActionSetRelayStateSchema
func (t JobActionSchema) AsJobActionSetRelayStateSchema() (JobActionSetRelayStateSchema, error) {
	var body JobActionSetRelayStateSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionSetRelayStateSchema overwrites any union data inside the JobActionSchema as the provided JobActionSetRelayStateSchema
func (t *JobActionSchema) FromJobActionSetRelayStateSchema(v JobActionSetRelayStateSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionSetRelayStateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSetRelayStateSchema
func (t *JobActionSchema) MergeJobActionSetRelayStateSchema(v JobActionSetRelayStateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetDisconnectorStateSchema returns the union data inside the JobActionSchema as a JobActionGetDisconnectorStateSchema
func (t JobActionSchema) AsJobActionGetDisconnectorStateSchema() (JobActionGetDisconnectorStateSchema, error) {
	var body JobActionGetDisconnectorStateSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetDisconnectorStateSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetDisconnectorStateSchema
func (t *JobActionSchema) FromJobActionGetDisconnectorStateSchema(v JobActionGetDisconnectorStateSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetDisconnectorStateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetDisconnectorStateSchema
func (t *JobActionSchema) MergeJobActionGetDisconnectorStateSchema(v JobActionGetDisconnectorStateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionSetDisconnectorStateSchema returns the union data inside the JobActionSchema as a JobActionSetDisconnectorStateSchema
func (t JobActionSchema) AsJobActionSetDisconnectorStateSchema() (JobActionSetDisconnectorStateSchema, error) {
	var body JobActionSetDisconnectorStateSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionSetDisconnectorStateSchema overwrites any union data inside the JobActionSchema as the provided JobActionSetDisconnectorStateSchema
func (t *JobActionSchema) FromJobActionSetDisconnectorStateSchema(v JobActionSetDisconnectorStateSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionSetDisconnectorStateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSetDisconnectorStateSchema
func (t *JobActionSchema) MergeJobActionSetDisconnectorStateSchema(v JobActionSetDisconnectorStateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetTouSchema returns the union data inside the JobActionSchema as a JobActionGetTouSchema
func (t JobActionSchema) AsJobActionGetTouSchema() (JobActionGetTouSchema, error) {
	var body JobActionGetTouSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetTouSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetTouSchema
func (t *JobActionSchema) FromJobActionGetTouSchema(v JobActionGetTouSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetTouSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetTouSchema
func (t *JobActionSchema) MergeJobActionGetTouSchema(v JobActionGetTouSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionSetTouSchema returns the union data inside the JobActionSchema as a JobActionSetTouSchema
func (t JobActionSchema) AsJobActionSetTouSchema() (JobActionSetTouSchema, error) {
	var body JobActionSetTouSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionSetTouSchema overwrites any union data inside the JobActionSchema as the provided JobActionSetTouSchema
func (t *JobActionSchema) FromJobActionSetTouSchema(v JobActionSetTouSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionSetTouSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSetTouSchema
func (t *JobActionSchema) MergeJobActionSetTouSchema(v JobActionSetTouSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionGetLimiterSchema returns the union data inside the JobActionSchema as a JobActionGetLimiterSchema
func (t JobActionSchema) AsJobActionGetLimiterSchema() (JobActionGetLimiterSchema, error) {
	var body JobActionGetLimiterSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionGetLimiterSchema overwrites any union data inside the JobActionSchema as the provided JobActionGetLimiterSchema
func (t *JobActionSchema) FromJobActionGetLimiterSchema(v JobActionGetLimiterSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionGetLimiterSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionGetLimiterSchema
func (t *JobActionSchema) MergeJobActionGetLimiterSchema(v JobActionGetLimiterSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionSetLimiterSchema returns the union data inside the JobActionSchema as a JobActionSetLimiterSchema
func (t JobActionSchema) AsJobActionSetLimiterSchema() (JobActionSetLimiterSchema, error) {
	var body JobActionSetLimiterSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionSetLimiterSchema overwrites any union data inside the JobActionSchema as the provided JobActionSetLimiterSchema
func (t *JobActionSchema) FromJobActionSetLimiterSchema(v JobActionSetLimiterSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionSetLimiterSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionSetLimiterSchema
func (t *JobActionSchema) MergeJobActionSetLimiterSchema(v JobActionSetLimiterSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionResetBillingPeriodSchema returns the union data inside the JobActionSchema as a JobActionResetBillingPeriodSchema
func (t JobActionSchema) AsJobActionResetBillingPeriodSchema() (JobActionResetBillingPeriodSchema, error) {
	var body JobActionResetBillingPeriodSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionResetBillingPeriodSchema overwrites any union data inside the JobActionSchema as the provided JobActionResetBillingPeriodSchema
func (t *JobActionSchema) FromJobActionResetBillingPeriodSchema(v JobActionResetBillingPeriodSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionResetBillingPeriodSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionResetBillingPeriodSchema
func (t *JobActionSchema) MergeJobActionResetBillingPeriodSchema(v JobActionResetBillingPeriodSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJobActionFwUpdateSchema returns the union data inside the JobActionSchema as a JobActionFwUpdateSchema
func (t JobActionSchema) AsJobActionFwUpdateSchema() (JobActionFwUpdateSchema, error) {
	var body JobActionFwUpdateSchema
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJobActionFwUpdateSchema overwrites any union data inside the JobActionSchema as the provided JobActionFwUpdateSchema
func (t *JobActionSchema) FromJobActionFwUpdateSchema(v JobActionFwUpdateSchema) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJobActionFwUpdateSchema performs a merge with any union data inside the JobActionSchema, using the provided JobActionFwUpdateSchema
func (t *JobActionSchema) MergeJobActionFwUpdateSchema(v JobActionFwUpdateSchema) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t JobActionSchema) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *JobActionSchema) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xc3XfbtpL/V3C4+9DuoeV8NN2Nn9aRlVy1iqUryb3t6fVRIXIkISEBFgBtqz363+/B",
	"B0lQJCXKpvIUhwQGmN8MBvNF/e0FLE4YBSqFd/W3J4INxFj/eR1IwujwRv0dggg4SdQD78qbbwANbxBb",
	"IbkBhPW43r+p53srxmMsvSsvTUno+Z7cJuBdeUJyQtfezrdE59sEZnqleuJqmiKfk0bof9AfnwbzxXTw",
	"aTibD6Z/oAs0zxdHRCDJ0BokwmhJoojQNXrAUQo+WjGO4AnHSQQ+IlRITCWmwFJhRgiX/GQwHY5vhv3r",
	"0WIyHX8cjgYHFkqAExaSAEco4WxFov3VIobDC/vKXWU4nQ4+3Y2upy0WoYxeNCzkoxCTaJs9Q4yjmFG5",
	"ibY5BhzWREjgJSYHvwxu57PmNSmCB6ASRWztTuuPxv2fG2cpTQgiFnzNpsx+u+0fmCO2NNhwRslf4Mx1",
	"xzkjRDEEEar/E8IDCaCHhkYJV4wHgLCUnCxTCWoRAdJHRJpXqzSKtuqRqO7U6NXo+rfFbH49HxxkkUOE",
	"t0hILHOJzlpMF83T1eo3w1l/fHs76M/H0xabCIkIGKUQSMare2lJTBwlpnY2H98d3IokMVyw1UUqAEm8",
	"jEo7aZosjk1WK4+Gn4eHDroiEJGYSOCKoCR0LdzFD80XR+ZPB4rCh+FoNLz9ZI1CLSEOGansxJmzmhH6",
	"+K/F3eSmUQQSc3XGV4THj5gDSpPQ4O/5HtA09q5+91yr5/levZWyLyqGxT43J97+R59Jz/eKA2pfOEqs",
	"Xlee1GuqHVr7wmqQHWL+cmRrnxf/q8Pd870cRe++7krJDr0orhQchkQBjaMJZwlwSUDfaZhuxyvv6ve/",
	"K2TyJ4RKWAN3H9E0XpafLBmLAFNvd+97NI0ipbzeleQp7Py9+8xsCskNlsi8WYJAWOuguuLy3SNMQ6VK",
	"hGcXk9aYr7DV6rIBZegVL1tEcQzZcDO4MkQ/NRTMgABTtNS3qr5dDePqRtTs+sgw6SPLmo+WhGK+9dW1",
	"olg0Wmn5Z8svEEjP954u1uzCPsxZ6RUicYdckDhhXCo5JFhuvCtvTeQmXfYCFl8G2yVnIsJLcbkBcfHm",
	"AidEXLIEKE6I/ncD4jJfwtvtfO9DGn097p98YUu0TCN7uQxvUJwKqaBIKfkzVUeSMyEQjiI0ToD+YzBD",
	"hU/U0q1RO5klEDQ5NfVK8IUthfYYMBIJBGRFAhRy8gBcy8isnZQVWNsP/ed/c1h5V95/XRa7vbTu2+VP",
	"bGk8rRER0m5q53sB4+oGOuTXOUMcDAv89t4TgVIBoTbKnKWJHmlRKx+MGtTMHd6GmRs9ssyMQWquidZx",
	"4iCp711ptmlVwnCjX2b6wChk/Io0UaoKoUvFshUTOgK6Vgr8uoYpEh7jx6rtzveye6cFAjM7tOD/EZYb",
	"xr7eTUf1/N9NRxk7dqi5+mio3Uqp1M3I8XEDFGG61UfF+ldKjkq6IaOwfwg4OS7dne9x+DMlHEJ1i+lj",
	"k8nbz9W4JMX7ffOSHSyJZSoGNI0PxQxCj9Im1ahrcYe+8l/7b/y3/g/FCpmVV+ZJjbpwCAq14bmDwZ8p",
	"pBDqk5pwFoAQhK6VAikv0yxLlAERxrPAK+VTYKpsO8SJRCtMIqH24xINUs6BSuWsg3YcDGUIKwOZiibk",
	"3osNFmgJQJVdDyCKal7DU6Lg7ylgLZcPmKu7Q3P4z7vB3UBdr9O729vh7SfP9/rjz5PRYK6f9q9v+4PR",
	"SP89+HUynA5uvPuSRE4zdrlSGcR6FdO2IpSIDYTXsiEoJDEYVZUVEGLMv0KIsItWWWmVY3WhSLQxTNox",
	"e95O6nXlZXuRqWhjUyrnZP8QWlJ156xvQgAbm082jMKIUDhdxImaiiJCAX0XsxDi71GQ06670axzVQu0",
	"IWZGZLbMBn5tTHHCWLQw9rhKW28OqSFoeNPymlcPFnqiohnjJxIrA/Na7yT/e9+R3JOCQ8TPuC/2elw4",
	"hUwYBevNHlKN8ux5kAyT/BI5Zea+Upw2ewac4Ogze8LZ9PsqZ/tjTtC7z+Nfr49oWsDiGNNwYn3QGnVj",
	"XB7StkzeP7579/bdYZn76pDjb7TUhomGZYYThMOQgxDKjVerqLE6fKhZtUnfn/DL1f0Je3ajDjR+SSbH",
	"Vd9V3hN0Y96fXA4nR7TjbCAm30YJNM4ySF4qKkUil1TSJJc8wOizOGa0SSbmLVoRiEKBxAZzezeqaMs6",
	"gbVhThFAHrn4KtF/Kxc8z23X+qnO6gd5//h4pxM2Tt4hilpY5HrwlD0to6DlsXpcmLTQSwVbEKoyde+3",
	"Pkw2g3UgfVXC6BPIfsSCr2fFaA1yoVO6L8WoINQRRuXU+D4yN07uVXlvcHaU3GzvQmd7u4CshmrH+NVk",
	"qffBHDwoaM6OoK6NiC5Qs5Q6RMpQrCAz5BzWaYT5xFSKzo4RyRZc2NpUF3BViXaIHKYop58V1Co4jky5",
	"4Ozw2bJEF6BlpDo+jpXCyT5Uk7xkeWadSzDH8UKuOIsb80JcmpDd+lhZvVS5oQci86ojZ5aSrH4hoGEn",
	"y+SyK8q+XR6jGqpdnqOaqnhFOaa2Kn32g5SVv7vALafVKVoZ1RqMIrz9Nj6BLkp35wy45Do2O275fB+w",
	"OUvPjpRkaRcIKTIdI1MtpZfwcSonFdt1jSIiZNFuo0vTS3AS0uiaIogTuUWYc6zLkZRJ9IAjEvoISxQB",
	"VhRovrOspJJwEECl29chkAoVcuJZvUHocJqHwBHWTG71uBBWhBaj1E6NLSUS4vZlsCI2rE0ZarZKgE1B",
	"gPxgavrmLjurcuk+goXtIbAm+qWaVkuzI7Vr7HvYBzGNHL3bT8eFDZU7ruft9ZdlnT5FB4VIA6VDqzTy",
	"9wrhPDXl8QcSAHoALnDWkDHe70bKE/cFNdNSZXXfzru7nd1NJuPpfFDTCKIOQ1ExXG5NxKILW9n8wXQ6",
	"1r0oMxYDAs4ZF2iDHwCxQFeCQhSmygPIXAdbOag02Wlqt+P5YjId9wezWWU/iiG1Ic2Uy4fTUzL+2fM9",
	"hyXP9/QGPd8rka7tt1D+zEG5qQF1zYHt0tW25L+wJf+FwdH+o0i7f5q6cOZPiBssccvs9DOWsZ6su8h9",
	"B9kmfQ4srAfTTaclPrPsWmvgD3hox8Bs4/mfQqMhYD2FRCkbcMpEN1vVet5sS4NnTazz9Nqv+pLJB9JP",
	"p2zgxTRKrtspKz9jViWGP2W9Z85s9CRaU9hLM2uj00YE53FVxFmyiOKsWUTRMos4+zY5HtFdjkd0n+MR",
	"rXI8s28WoopuQ1RxnhBVHAtRZ+cPUUU3IaroNkQV7ULU/Sv0TBBtadBNqcih1BVQtZ9EWJAqHZAVN3Bk",
	"o3jbZWejeNOPdFrMbNY6IWYuTagJ9LK6+5Cu2LH1a5td8mbR6xcVhuFJAqc4amp+TdJlRAKn79Utxx/t",
	"1DoeCPzElqbxU52FvxiF5v6yv5xu1BN2UR9glPCvgbIh7BioMLXPwoPfapWD9S9sWQSpt/qzh1tm4l0/",
	"78ZuGXPXxMzfie9PiZqd3Xy8nl+PslBZbSJgaRTaSNlJR4UpqJOD0QpLHJlVy8Gz4ssJmDXh2kDZSPt4",
	"d/o5G9OrncPte9Pdz2LqOjQgTkwhtMpf0dSSjVOgWpRzvl0GCJVv37hNL+/fH+2wghUoh7epvSbUVzGh",
	"SEDAaKh0bsW4rQhlSrMiXMi8U9cRyt7mfvzB3dz//fjDq1fO/l7V7c/034p2XaQKbzuh17pUFOOnm5Rj",
	"Q7S2ydFsWJ0S0+rtoHFcIGWe//dNieXX7+p4TjhhnMhtg321bw/gvKcExzDmIPn2Rgn6NB3Q8zIdOMr6",
	"+/dHNrKrN6CmI1dZ0Pbd686GXti+rrv5O+5etzSPNq9n4/Z710vmv9K6nr09T+d6LpDTOwjdjwuscOqT",
	"2Udu//0bdeef2PZuP0fJJrl3XnHhPbvX3Nzl4tBFL8qZXaHz8kpbDmWffRsaaU/BJsyz0tAzqjmlusKu",
	"ka/cQz2pnd8ibOd0DHC7Zv4my9HQz29TyHVO3POz3B/KoVjrg0LoOgIUMCoJTVkq0FJ/tc1WNf0Q5SMk",
	"mm/yag/H0n7A3fqqNJ9UHkP+hXj9ohdxpNW1QEoLnCCWrMKbySD/5YO2Z++kfX8CCpwEerMli7urns0X",
	"AtIBFlqVzoZF46HqFAunJnXKtzpHTqRB5sxwOLpR1L1rXEf9rq63yvHu9gxC5k5W3caUkgZTo940d3Ad",
	"jrYtXpZ8zk9HhjmryT1P1lmjUaOwleEUEsdJ8yWpX+dJiRPb2tpB3gi1teDfyE7tuhWZeJ7MMkvl/orL",
	"GY1UjYK91Eg1Iny6S2G6Ox6J3CAi88gF01BFC5r5Oq3O3jW0bNq3mfaZH01oa0QKZ+5YPNdAVweZVbq5",
	"olfJOoSKon71pyyOL+KMCVmqXFa/za9d1BwM9YjYvK5y+3CgwYYYk0gvuWL/X/y4Qy9g+rNHHCsaff0c",
	"jfBSIAlYvUm5mrWRMhFXl5ePj4+98uRLQkNQMWFvI+NIwRWRAKjQgFmyH2aji9e9VxVqSmUFS3kAPcbX",
	"l3aiuMzG68SsjKD4cOl6MtQfikbmdxpsGs7zvQfgwojlVc9OtQfDu/Le9l713ipVxHIjvCsVFez+EwAA",
	"//8iQl75aUsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../driver/driverdata/driverdata.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
