package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"

	"github.com/cybroslabs/hes-2-apis/graph/model"
)

// CreateBulk is the resolver for the createBulk field.
func (r *queryResolver) CreateBulk(ctx context.Context) (*model.StringValue, error) {
	panic(fmt.Errorf("not implemented: CreateBulk - createBulk"))
}

// ListBulks is the resolver for the listBulks field.
func (r *queryResolver) ListBulks(ctx context.Context) (*model.ListOfBulk, error) {
	panic(fmt.Errorf("not implemented: ListBulks - listBulks"))
}

// GetBulk is the resolver for the getBulk field.
func (r *queryResolver) GetBulk(ctx context.Context) (*model.Bulk, error) {
	panic(fmt.Errorf("not implemented: GetBulk - getBulk"))
}

// CancelBulk is the resolver for the cancelBulk field.
func (r *queryResolver) CancelBulk(ctx context.Context) (*model.Empty, error) {
	panic(fmt.Errorf("not implemented: CancelBulk - cancelBulk"))
}

// GetConfig is the resolver for the getConfig field.
func (r *queryResolver) GetConfig(ctx context.Context) (*model.SystemConfig, error) {
	panic(fmt.Errorf("not implemented: GetConfig - getConfig"))
}

// SetConfig is the resolver for the setConfig field.
func (r *queryResolver) SetConfig(ctx context.Context) (*model.Empty, error) {
	panic(fmt.Errorf("not implemented: SetConfig - setConfig"))
}

// CreateCommunicationUnit is the resolver for the createCommunicationUnit field.
func (r *queryResolver) CreateCommunicationUnit(ctx context.Context) (*model.StringValue, error) {
	panic(fmt.Errorf("not implemented: CreateCommunicationUnit - createCommunicationUnit"))
}

// ListCommunicationUnits is the resolver for the listCommunicationUnits field.
func (r *queryResolver) ListCommunicationUnits(ctx context.Context) (*model.ListOfCommunicationUnit, error) {
	panic(fmt.Errorf("not implemented: ListCommunicationUnits - listCommunicationUnits"))
}

// GetCommunicationUnit is the resolver for the getCommunicationUnit field.
func (r *queryResolver) GetCommunicationUnit(ctx context.Context) (*model.CommunicationUnit, error) {
	panic(fmt.Errorf("not implemented: GetCommunicationUnit - getCommunicationUnit"))
}

// CreateCommunicationUnitBus is the resolver for the createCommunicationUnitBus field.
func (r *queryResolver) CreateCommunicationUnitBus(ctx context.Context) (*model.StringValue, error) {
	panic(fmt.Errorf("not implemented: CreateCommunicationUnitBus - createCommunicationUnitBus"))
}

// ListCommunicationUnitBuses is the resolver for the listCommunicationUnitBuses field.
func (r *queryResolver) ListCommunicationUnitBuses(ctx context.Context) (*model.ListOfCommunicationUnitBus, error) {
	panic(fmt.Errorf("not implemented: ListCommunicationUnitBuses - listCommunicationUnitBuses"))
}

// AddCommunicationUnitsToBus is the resolver for the addCommunicationUnitsToBus field.
func (r *queryResolver) AddCommunicationUnitsToBus(ctx context.Context) (*model.Empty, error) {
	panic(fmt.Errorf("not implemented: AddCommunicationUnitsToBus - addCommunicationUnitsToBus"))
}

// RemoveCommunicationUnitsFromBus is the resolver for the removeCommunicationUnitsFromBus field.
func (r *queryResolver) RemoveCommunicationUnitsFromBus(ctx context.Context) (*model.Empty, error) {
	panic(fmt.Errorf("not implemented: RemoveCommunicationUnitsFromBus - removeCommunicationUnitsFromBus"))
}

// CreateDevice is the resolver for the createDevice field.
func (r *queryResolver) CreateDevice(ctx context.Context) (*model.StringValue, error) {
	panic(fmt.Errorf("not implemented: CreateDevice - createDevice"))
}

// ListDevices is the resolver for the listDevices field.
func (r *queryResolver) ListDevices(ctx context.Context) (*model.ListOfDevice, error) {
	panic(fmt.Errorf("not implemented: ListDevices - listDevices"))
}

// GetDevice is the resolver for the getDevice field.
func (r *queryResolver) GetDevice(ctx context.Context) (*model.Device, error) {
	panic(fmt.Errorf("not implemented: GetDevice - getDevice"))
}

// SetDeviceCommunicationUnits is the resolver for the setDeviceCommunicationUnits field.
func (r *queryResolver) SetDeviceCommunicationUnits(ctx context.Context) (*model.Empty, error) {
	panic(fmt.Errorf("not implemented: SetDeviceCommunicationUnits - setDeviceCommunicationUnits"))
}

// GetDeviceCommunicationUnits is the resolver for the getDeviceCommunicationUnits field.
func (r *queryResolver) GetDeviceCommunicationUnits(ctx context.Context) (*model.ListOfDeviceCommunicationUnit, error) {
	panic(fmt.Errorf("not implemented: GetDeviceCommunicationUnits - getDeviceCommunicationUnits"))
}

// CreateDeviceGroup is the resolver for the createDeviceGroup field.
func (r *queryResolver) CreateDeviceGroup(ctx context.Context) (*model.StringValue, error) {
	panic(fmt.Errorf("not implemented: CreateDeviceGroup - createDeviceGroup"))
}

// ListDeviceGroups is the resolver for the listDeviceGroups field.
func (r *queryResolver) ListDeviceGroups(ctx context.Context) (*model.ListOfDeviceGroup, error) {
	panic(fmt.Errorf("not implemented: ListDeviceGroups - listDeviceGroups"))
}

// GetDeviceGroup is the resolver for the getDeviceGroup field.
func (r *queryResolver) GetDeviceGroup(ctx context.Context) (*model.DeviceGroup, error) {
	panic(fmt.Errorf("not implemented: GetDeviceGroup - getDeviceGroup"))
}

// AddDevicesToGroup is the resolver for the addDevicesToGroup field.
func (r *queryResolver) AddDevicesToGroup(ctx context.Context) (*model.Empty, error) {
	panic(fmt.Errorf("not implemented: AddDevicesToGroup - addDevicesToGroup"))
}

// RemoveDevicesFromGroup is the resolver for the removeDevicesFromGroup field.
func (r *queryResolver) RemoveDevicesFromGroup(ctx context.Context) (*model.Empty, error) {
	panic(fmt.Errorf("not implemented: RemoveDevicesFromGroup - removeDevicesFromGroup"))
}

// ListModemPools is the resolver for the listModemPools field.
func (r *queryResolver) ListModemPools(ctx context.Context) (*model.ListOfModemPool, error) {
	panic(fmt.Errorf("not implemented: ListModemPools - listModemPools"))
}

// GetModemPool is the resolver for the getModemPool field.
func (r *queryResolver) GetModemPool(ctx context.Context) (*model.ModemPool, error) {
	panic(fmt.Errorf("not implemented: GetModemPool - getModemPool"))
}

// CreateModemPool is the resolver for the createModemPool field.
func (r *queryResolver) CreateModemPool(ctx context.Context) (*model.StringValue, error) {
	panic(fmt.Errorf("not implemented: CreateModemPool - createModemPool"))
}

// UpdateModemPool is the resolver for the updateModemPool field.
func (r *queryResolver) UpdateModemPool(ctx context.Context) (*model.Empty, error) {
	panic(fmt.Errorf("not implemented: UpdateModemPool - updateModemPool"))
}

// DeleteModemPool is the resolver for the deleteModemPool field.
func (r *queryResolver) DeleteModemPool(ctx context.Context) (*model.Empty, error) {
	panic(fmt.Errorf("not implemented: DeleteModemPool - deleteModemPool"))
}

// CreateModem is the resolver for the createModem field.
func (r *queryResolver) CreateModem(ctx context.Context) (*model.StringValue, error) {
	panic(fmt.Errorf("not implemented: CreateModem - createModem"))
}

// UpdateModem is the resolver for the updateModem field.
func (r *queryResolver) UpdateModem(ctx context.Context) (*model.Empty, error) {
	panic(fmt.Errorf("not implemented: UpdateModem - updateModem"))
}

// DeleteModem is the resolver for the deleteModem field.
func (r *queryResolver) DeleteModem(ctx context.Context) (*model.Empty, error) {
	panic(fmt.Errorf("not implemented: DeleteModem - deleteModem"))
}

// ListDrivers is the resolver for the listDrivers field.
func (r *queryResolver) ListDrivers(ctx context.Context) (*model.ListOfDriver, error) {
	panic(fmt.Errorf("not implemented: ListDrivers - listDrivers"))
}

// GetDriver is the resolver for the getDriver field.
func (r *queryResolver) GetDriver(ctx context.Context) (*model.Driver, error) {
	panic(fmt.Errorf("not implemented: GetDriver - getDriver"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) ListCommunicationUnitsBuses(ctx context.Context) (*model.ListOfCommunicationUnitBus, error) {
	panic(fmt.Errorf("not implemented: ListCommunicationUnitsBuses - listCommunicationUnitsBuses"))
}
*/
