// Package device provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package device

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/cybroslabs/hes-2-apis/openapi/openhes/job"
	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CommunicationUnitID The ID of the communication unit. The ID must be unique across the OpenHES components.
type CommunicationUnitID = openapi_types.UUID

// CommunicationUnitSchema Schema that holds the communication unit info.
type CommunicationUnitSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// ExternalID The public ID of the device.
	ExternalID *string `json:"externalID"`

	// Id The ID of the communication unit. The ID must be unique across the OpenHES components.
	Id CommunicationUnitID `json:"id"`

	// Name The name of the communication unit.
	Name string `json:"name"`
}

// DeviceGroupID The ID of the device group. The ID must be unique across the OpenHES components.
type DeviceGroupID = openapi_types.UUID

// DeviceGroupSchema Schema that holds the device group info.
type DeviceGroupSchema struct {
	// ExternalID The public ID of the device.
	ExternalID *string `json:"externalID"`

	// Id The ID of the device group. The ID must be unique across the OpenHES components.
	Id DeviceGroupID `json:"id"`

	// Name The name of the device group.
	Name string `json:"name"`
}

// DeviceID The ID of the device. The ID must be unique across the OpenHES components.
type DeviceID = openapi_types.UUID

// DeviceSchema Schema that holds the device info.
type DeviceSchema struct {
	// Attributes Schema that holds a set of attributes and their values. The key is the property name and the value is the property value. The value can be of type string, integer, number, boolean, binary, or null.
	Attributes externalRef0.AttributesSchema `json:"attributes"`

	// ExternalID The public ID of the device.
	ExternalID *string `json:"externalID"`

	// Id The ID of the device. The ID must be unique across the OpenHES components.
	Id DeviceID `json:"id"`

	// Name The name of the device.
	Name string `json:"name"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9yWz27bOBDGX2Uwu0daSnZvOm02XmwNBEiAtKc0B4oaW2wlUiGHSQxD716Qkv/VNpK0",
	"CFA0lxijoeabb34UuUJl284aMuyxWKFXNbUy/bxgdroMTP42BWNMVpVmbY1sbpztyLGmlCvN8nqOxd0K",
	"edkRFujZabPAXmwi2jAtyO2GTGjL/UhpbUPSYH8v0ISmkWVDWLAL1AusyCunu1gfCxxEAdeSobZN5UGC",
	"JwY7B7lRDtJUwDVpB4+yCeQz+FgTfKUlaB8fQDf0sQQjW1qnD8kHKSk6vGFIUNJASbFk1A9D0wLGVgUM",
	"DQoY2xJQaiPdUoB1ENvLPhsU695t+YUUo8DnycJOxuCmlWw7jt2UiW476zjOoJNcY4ELzXUoM2XbXC1L",
	"Z30jS5/X5Cd/TWSnfW47MrLT6X9NPt+UwL4XeGnbNhitZLT5k9E8m8aX73sfHZhNU981gdpdAsFoHjya",
	"TaENnqNDweiHQCCVs34w9boj8+G/W9jiN5gxt66VjAWGoKutORueDgVu6XwJkONiQZu5HYp3+1BvHS9W",
	"+KejORb4R75VnI+7JT/YKr1AemZyRjan/OtC2Wi1Y2NFj1pRBuu/pGh/ExyxQ1cviTs20V5g5P24srQT",
	"Ts826Wq1uSKziMSdH6jqBTp6CNpRhcUdpjmmcmLX0/vvye8FTpMH/zsbupe5GwyDRcx+T+J2RL2NtV2B",
	"Jyn7ZTjZ9/7VhOxN4SfYOI3Da0l4fwZ+aPy/+edlM6M3EvOO35G4MLoepShrWKp0QFIrdZNuInP7z/Zs",
	"jEfl+sUFXqY4XMnSA5OMT4KLq2rmzhd5/vT0lO0vzrWp6HlCJqu5bfDgphI/wNbAxc0MWltR42Fu3RpF",
	"FNhoRcYn40YR/95eTc6zs4Pa8cj2NjhFmXWLfFzo83V+L5A1N/SKoo/k/CDvLBuXjhcDLPDvbKgerxQe",
	"i0hJ/y0AAP//MDR/rCoKAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../job/job.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
