// Editions version of proto3 file

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.3
// source: pbdataproxy-models.proto

package pbdataproxymodels

import (
	pbdrivermodels "github.com/cybroslabs/hes-2-apis/protobuf/pbdrivermodels"
	pbtaskmastermodels "github.com/cybroslabs/hes-2-apis/protobuf/pbtaskmastermodels"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bulk statuses
type BulkStatusCode int32

const (
	// The job is waiting in the queue
	BulkStatusCode_BULK_STATUS_QUEUED BulkStatusCode = 0
	// The job is running
	BulkStatusCode_BULK_STATUS_RUNNING BulkStatusCode = 1
	// The job is completed
	BulkStatusCode_BULK_STATUS_COMPLETED BulkStatusCode = 2
	// The job is cancelled
	BulkStatusCode_BULK_STATUS_CANCELLED BulkStatusCode = 3
	// The job has expired
	BulkStatusCode_BULK_STATUS_EXPIRED BulkStatusCode = 4
)

// Enum value maps for BulkStatusCode.
var (
	BulkStatusCode_name = map[int32]string{
		0: "BULK_STATUS_QUEUED",
		1: "BULK_STATUS_RUNNING",
		2: "BULK_STATUS_COMPLETED",
		3: "BULK_STATUS_CANCELLED",
		4: "BULK_STATUS_EXPIRED",
	}
	BulkStatusCode_value = map[string]int32{
		"BULK_STATUS_QUEUED":    0,
		"BULK_STATUS_RUNNING":   1,
		"BULK_STATUS_COMPLETED": 2,
		"BULK_STATUS_CANCELLED": 3,
		"BULK_STATUS_EXPIRED":   4,
	}
)

func (x BulkStatusCode) Enum() *BulkStatusCode {
	p := new(BulkStatusCode)
	*p = x
	return p
}

func (x BulkStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BulkStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_pbdataproxy_models_proto_enumTypes[0].Descriptor()
}

func (BulkStatusCode) Type() protoreflect.EnumType {
	return &file_pbdataproxy_models_proto_enumTypes[0]
}

func (x BulkStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// RestApi -> DataProxy
type CreateBulkRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Spec *BulkSpec              `protobuf:"bytes,1,opt,name=spec" json:"spec,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateBulkRequest) Reset() {
	*x = CreateBulkRequest{}
	mi := &file_pbdataproxy_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBulkRequest) ProtoMessage() {}

func (x *CreateBulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataproxy_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateBulkRequest) GetSpec() *BulkSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *CreateBulkRequest) SetSpec(v *BulkSpec) {
	x.xxx_hidden_Spec = v
}

func (x *CreateBulkRequest) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *CreateBulkRequest) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

type CreateBulkRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Spec *BulkSpec
}

func (b0 CreateBulkRequest_builder) Build() *CreateBulkRequest {
	m0 := &CreateBulkRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Spec = b.Spec
	return m0
}

// Sub-message - holds the bulk job specification.
type BulkSpec struct {
	state                    protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_BulkId        *string                          `protobuf:"bytes,1,opt,name=bulk_id,json=bulkId" json:"bulk_id,omitempty"`
	xxx_hidden_CorrelationId *string                          `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId" json:"correlation_id,omitempty"`
	xxx_hidden_OrgId         *string                          `protobuf:"bytes,3,opt,name=org_id,json=orgId" json:"org_id,omitempty"`
	xxx_hidden_DriverType    *string                          `protobuf:"bytes,4,opt,name=driver_type,json=driverType" json:"driver_type,omitempty"`
	xxx_hidden_Devices       *[]*pbtaskmastermodels.JobDevice `protobuf:"bytes,5,rep,name=devices" json:"devices,omitempty"`
	xxx_hidden_Settings      *pbdrivermodels.JobSettings      `protobuf:"bytes,6,opt,name=settings" json:"settings,omitempty"`
	xxx_hidden_JobActions    *[]*pbdrivermodels.JobAction     `protobuf:"bytes,7,rep,name=job_actions,json=jobActions" json:"job_actions,omitempty"`
	xxx_hidden_WebhookUrl    *string                          `protobuf:"bytes,8,opt,name=webhook_url,json=webhookUrl" json:"webhook_url,omitempty"`
	xxx_hidden_UserId        *string                          `protobuf:"bytes,9,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BulkSpec) Reset() {
	*x = BulkSpec{}
	mi := &file_pbdataproxy_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSpec) ProtoMessage() {}

func (x *BulkSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataproxy_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BulkSpec) GetBulkId() string {
	if x != nil {
		if x.xxx_hidden_BulkId != nil {
			return *x.xxx_hidden_BulkId
		}
		return ""
	}
	return ""
}

func (x *BulkSpec) GetCorrelationId() string {
	if x != nil {
		if x.xxx_hidden_CorrelationId != nil {
			return *x.xxx_hidden_CorrelationId
		}
		return ""
	}
	return ""
}

func (x *BulkSpec) GetOrgId() string {
	if x != nil {
		if x.xxx_hidden_OrgId != nil {
			return *x.xxx_hidden_OrgId
		}
		return ""
	}
	return ""
}

func (x *BulkSpec) GetDriverType() string {
	if x != nil {
		if x.xxx_hidden_DriverType != nil {
			return *x.xxx_hidden_DriverType
		}
		return ""
	}
	return ""
}

func (x *BulkSpec) GetDevices() []*pbtaskmastermodels.JobDevice {
	if x != nil {
		if x.xxx_hidden_Devices != nil {
			return *x.xxx_hidden_Devices
		}
	}
	return nil
}

func (x *BulkSpec) GetSettings() *pbdrivermodels.JobSettings {
	if x != nil {
		return x.xxx_hidden_Settings
	}
	return nil
}

func (x *BulkSpec) GetJobActions() []*pbdrivermodels.JobAction {
	if x != nil {
		if x.xxx_hidden_JobActions != nil {
			return *x.xxx_hidden_JobActions
		}
	}
	return nil
}

func (x *BulkSpec) GetWebhookUrl() string {
	if x != nil {
		if x.xxx_hidden_WebhookUrl != nil {
			return *x.xxx_hidden_WebhookUrl
		}
		return ""
	}
	return ""
}

func (x *BulkSpec) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *BulkSpec) SetBulkId(v string) {
	x.xxx_hidden_BulkId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *BulkSpec) SetCorrelationId(v string) {
	x.xxx_hidden_CorrelationId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *BulkSpec) SetOrgId(v string) {
	x.xxx_hidden_OrgId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *BulkSpec) SetDriverType(v string) {
	x.xxx_hidden_DriverType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *BulkSpec) SetDevices(v []*pbtaskmastermodels.JobDevice) {
	x.xxx_hidden_Devices = &v
}

func (x *BulkSpec) SetSettings(v *pbdrivermodels.JobSettings) {
	x.xxx_hidden_Settings = v
}

func (x *BulkSpec) SetJobActions(v []*pbdrivermodels.JobAction) {
	x.xxx_hidden_JobActions = &v
}

func (x *BulkSpec) SetWebhookUrl(v string) {
	x.xxx_hidden_WebhookUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *BulkSpec) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *BulkSpec) HasBulkId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BulkSpec) HasCorrelationId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *BulkSpec) HasOrgId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *BulkSpec) HasDriverType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *BulkSpec) HasSettings() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Settings != nil
}

func (x *BulkSpec) HasWebhookUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *BulkSpec) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *BulkSpec) ClearBulkId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_BulkId = nil
}

func (x *BulkSpec) ClearCorrelationId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CorrelationId = nil
}

func (x *BulkSpec) ClearOrgId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_OrgId = nil
}

func (x *BulkSpec) ClearDriverType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_DriverType = nil
}

func (x *BulkSpec) ClearSettings() {
	x.xxx_hidden_Settings = nil
}

func (x *BulkSpec) ClearWebhookUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_WebhookUrl = nil
}

func (x *BulkSpec) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_UserId = nil
}

type BulkSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BulkId        *string
	CorrelationId *string
	OrgId         *string
	DriverType    *string
	Devices       []*pbtaskmastermodels.JobDevice
	Settings      *pbdrivermodels.JobSettings
	JobActions    []*pbdrivermodels.JobAction
	WebhookUrl    *string
	UserId        *string
}

func (b0 BulkSpec_builder) Build() *BulkSpec {
	m0 := &BulkSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.BulkId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_BulkId = b.BulkId
	}
	if b.CorrelationId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_CorrelationId = b.CorrelationId
	}
	if b.OrgId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_OrgId = b.OrgId
	}
	if b.DriverType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_DriverType = b.DriverType
	}
	x.xxx_hidden_Devices = &b.Devices
	x.xxx_hidden_Settings = b.Settings
	x.xxx_hidden_JobActions = &b.JobActions
	if b.WebhookUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_WebhookUrl = b.WebhookUrl
	}
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_UserId = b.UserId
	}
	return m0
}

// Sub-message - holds the bulk job status.
type BulkStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status      BulkStatusCode         `protobuf:"varint,1,opt,name=status,enum=io.clbs.openhes.pbdataproxy.BulkStatusCode" json:"status,omitempty"`
	xxx_hidden_Jobs        *[]*BulkJobStatus      `protobuf:"bytes,2,rep,name=jobs" json:"jobs,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BulkStatus) Reset() {
	*x = BulkStatus{}
	mi := &file_pbdataproxy_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkStatus) ProtoMessage() {}

func (x *BulkStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataproxy_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BulkStatus) GetStatus() BulkStatusCode {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Status
		}
	}
	return BulkStatusCode_BULK_STATUS_QUEUED
}

func (x *BulkStatus) GetJobs() []*BulkJobStatus {
	if x != nil {
		if x.xxx_hidden_Jobs != nil {
			return *x.xxx_hidden_Jobs
		}
	}
	return nil
}

func (x *BulkStatus) SetStatus(v BulkStatusCode) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *BulkStatus) SetJobs(v []*BulkJobStatus) {
	x.xxx_hidden_Jobs = &v
}

func (x *BulkStatus) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BulkStatus) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = BulkStatusCode_BULK_STATUS_QUEUED
}

type BulkStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status *BulkStatusCode
	Jobs   []*BulkJobStatus
}

func (b0 BulkStatus_builder) Build() *BulkStatus {
	m0 := &BulkStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Status = *b.Status
	}
	x.xxx_hidden_Jobs = &b.Jobs
	return m0
}

type BulkJobStatus struct {
	state                  protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_JobId       *string                       `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	xxx_hidden_Status      *pbtaskmastermodels.JobStatus `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BulkJobStatus) Reset() {
	*x = BulkJobStatus{}
	mi := &file_pbdataproxy_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkJobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkJobStatus) ProtoMessage() {}

func (x *BulkJobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataproxy_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BulkJobStatus) GetJobId() string {
	if x != nil {
		if x.xxx_hidden_JobId != nil {
			return *x.xxx_hidden_JobId
		}
		return ""
	}
	return ""
}

func (x *BulkJobStatus) GetStatus() *pbtaskmastermodels.JobStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *BulkJobStatus) SetJobId(v string) {
	x.xxx_hidden_JobId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *BulkJobStatus) SetStatus(v *pbtaskmastermodels.JobStatus) {
	x.xxx_hidden_Status = v
}

func (x *BulkJobStatus) HasJobId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BulkJobStatus) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *BulkJobStatus) ClearJobId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_JobId = nil
}

func (x *BulkJobStatus) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type BulkJobStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	JobId  *string
	Status *pbtaskmastermodels.JobStatus
}

func (b0 BulkJobStatus_builder) Build() *BulkJobStatus {
	m0 := &BulkJobStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.JobId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_JobId = b.JobId
	}
	x.xxx_hidden_Status = b.Status
	return m0
}

// DataProxy -> RestApi - the message holds the bulk info and it's status.
type Bulk struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Spec   *BulkSpec              `protobuf:"bytes,1,opt,name=spec" json:"spec,omitempty"`
	xxx_hidden_Status *BulkStatus            `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Bulk) Reset() {
	*x = Bulk{}
	mi := &file_pbdataproxy_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bulk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bulk) ProtoMessage() {}

func (x *Bulk) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataproxy_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Bulk) GetSpec() *BulkSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *Bulk) GetStatus() *BulkStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *Bulk) SetSpec(v *BulkSpec) {
	x.xxx_hidden_Spec = v
}

func (x *Bulk) SetStatus(v *BulkStatus) {
	x.xxx_hidden_Status = v
}

func (x *Bulk) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *Bulk) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *Bulk) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *Bulk) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type Bulk_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Spec   *BulkSpec
	Status *BulkStatus
}

func (b0 Bulk_builder) Build() *Bulk {
	m0 := &Bulk{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

// RestApi -> DataProxy - the message holds data for bulk listing request.
type GetBulksReuqest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Tfrom       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=tfrom" json:"tfrom,omitempty"`
	xxx_hidden_Tto         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=tto" json:"tto,omitempty"`
	xxx_hidden_IncludeData bool                   `protobuf:"varint,3,opt,name=include_data,json=includeData" json:"include_data,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetBulksReuqest) Reset() {
	*x = GetBulksReuqest{}
	mi := &file_pbdataproxy_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulksReuqest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulksReuqest) ProtoMessage() {}

func (x *GetBulksReuqest) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataproxy_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBulksReuqest) GetTfrom() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Tfrom
	}
	return nil
}

func (x *GetBulksReuqest) GetTto() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Tto
	}
	return nil
}

func (x *GetBulksReuqest) GetIncludeData() bool {
	if x != nil {
		return x.xxx_hidden_IncludeData
	}
	return false
}

func (x *GetBulksReuqest) SetTfrom(v *timestamppb.Timestamp) {
	x.xxx_hidden_Tfrom = v
}

func (x *GetBulksReuqest) SetTto(v *timestamppb.Timestamp) {
	x.xxx_hidden_Tto = v
}

func (x *GetBulksReuqest) SetIncludeData(v bool) {
	x.xxx_hidden_IncludeData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *GetBulksReuqest) HasTfrom() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tfrom != nil
}

func (x *GetBulksReuqest) HasTto() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tto != nil
}

func (x *GetBulksReuqest) HasIncludeData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetBulksReuqest) ClearTfrom() {
	x.xxx_hidden_Tfrom = nil
}

func (x *GetBulksReuqest) ClearTto() {
	x.xxx_hidden_Tto = nil
}

func (x *GetBulksReuqest) ClearIncludeData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_IncludeData = false
}

type GetBulksReuqest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Tfrom       *timestamppb.Timestamp
	Tto         *timestamppb.Timestamp
	IncludeData *bool
}

func (b0 GetBulksReuqest_builder) Build() *GetBulksReuqest {
	m0 := &GetBulksReuqest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Tfrom = b.Tfrom
	x.xxx_hidden_Tto = b.Tto
	if b.IncludeData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_IncludeData = *b.IncludeData
	}
	return m0
}

// DataProxy -> RestApi - the message holds list of bulks.
type ArrayOfBulk struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*Bulk               `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ArrayOfBulk) Reset() {
	*x = ArrayOfBulk{}
	mi := &file_pbdataproxy_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayOfBulk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayOfBulk) ProtoMessage() {}

func (x *ArrayOfBulk) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataproxy_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ArrayOfBulk) GetItems() []*Bulk {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *ArrayOfBulk) SetItems(v []*Bulk) {
	x.xxx_hidden_Items = &v
}

type ArrayOfBulk_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*Bulk
}

func (b0 ArrayOfBulk_builder) Build() *ArrayOfBulk {
	m0 := &ArrayOfBulk{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

// RestApi -> DataProxt - the message holds single bulk request.
type GetBulkRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BulkId      *string                `protobuf:"bytes,1,opt,name=bulk_id,json=bulkId" json:"bulk_id,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetBulkRequest) Reset() {
	*x = GetBulkRequest{}
	mi := &file_pbdataproxy_models_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulkRequest) ProtoMessage() {}

func (x *GetBulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataproxy_models_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBulkRequest) GetBulkId() string {
	if x != nil {
		if x.xxx_hidden_BulkId != nil {
			return *x.xxx_hidden_BulkId
		}
		return ""
	}
	return ""
}

func (x *GetBulkRequest) SetBulkId(v string) {
	x.xxx_hidden_BulkId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetBulkRequest) HasBulkId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetBulkRequest) ClearBulkId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_BulkId = nil
}

type GetBulkRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BulkId *string
}

func (b0 GetBulkRequest_builder) Build() *GetBulkRequest {
	m0 := &GetBulkRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.BulkId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_BulkId = b.BulkId
	}
	return m0
}

// RestApi -> DataProxy - request to get the job status.
type GetJobStatusRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_JobId       *string                `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_pbdataproxy_models_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataproxy_models_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		if x.xxx_hidden_JobId != nil {
			return *x.xxx_hidden_JobId
		}
		return ""
	}
	return ""
}

func (x *GetJobStatusRequest) SetJobId(v string) {
	x.xxx_hidden_JobId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetJobStatusRequest) HasJobId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetJobStatusRequest) ClearJobId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_JobId = nil
}

type GetJobStatusRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	JobId *string
}

func (b0 GetJobStatusRequest_builder) Build() *GetJobStatusRequest {
	m0 := &GetJobStatusRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.JobId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_JobId = b.JobId
	}
	return m0
}

// DataProxy -> RestApi - the message holds the job status.
type BulkJob struct {
	state             protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Status *pbtaskmastermodels.JobStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BulkJob) Reset() {
	*x = BulkJob{}
	mi := &file_pbdataproxy_models_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkJob) ProtoMessage() {}

func (x *BulkJob) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataproxy_models_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BulkJob) GetStatus() *pbtaskmastermodels.JobStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *BulkJob) SetStatus(v *pbtaskmastermodels.JobStatus) {
	x.xxx_hidden_Status = v
}

func (x *BulkJob) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *BulkJob) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type BulkJob_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status *pbtaskmastermodels.JobStatus
}

func (b0 BulkJob_builder) Build() *BulkJob {
	m0 := &BulkJob{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	return m0
}

var File_pbdataproxy_models_proto protoreflect.FileDescriptor

var file_pbdataproxy_models_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x62, 0x64, 0x61, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2d, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x69, 0x6f, 0x2e, 0x63,
	0x6c, 0x62, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x68, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x64, 0x61,
	0x74, 0x61, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x70, 0x62, 0x74, 0x61, 0x73, 0x6b, 0x6d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x15, 0x70, 0x62, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x04,
	0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x69, 0x6f, 0x2e,
	0x63, 0x6c, 0x62, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x68, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x64,
	0x61, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x42, 0x75, 0x6c, 0x6b, 0x53, 0x70, 0x65,
	0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x88, 0x03, 0x0a, 0x08, 0x42, 0x75, 0x6c, 0x6b,
	0x53, 0x70, 0x65, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x75, 0x6c, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x6c, 0x6b, 0x49, 0x64, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x41, 0x0a, 0x07,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x62, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x68, 0x65, 0x73, 0x2e,
	0x70, 0x62, 0x74, 0x61, 0x73, 0x6b, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12,
	0x41, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x62, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x68, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x12, 0x44, 0x0a, 0x0b, 0x6a, 0x6f, 0x62, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x62,
	0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x68, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x64, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x6a, 0x6f,
	0x62, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x65, 0x62, 0x68,
	0x6f, 0x6f, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77,
	0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x91, 0x01, 0x0a, 0x0a, 0x42, 0x75, 0x6c, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x43, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2b, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x62, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x68, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x64, 0x61, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e,
	0x42, 0x75, 0x6c, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3e, 0x0a, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x62, 0x73, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x68, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x64, 0x61, 0x74, 0x61, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x2e, 0x42, 0x75, 0x6c, 0x6b, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x22, 0x67, 0x0a, 0x0d, 0x42, 0x75, 0x6c, 0x6b, 0x4a, 0x6f,
	0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x3f,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x62, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x68, 0x65, 0x73,
	0x2e, 0x70, 0x62, 0x74, 0x61, 0x73, 0x6b, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4a, 0x6f,
	0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x82, 0x01, 0x0a, 0x04, 0x42, 0x75, 0x6c, 0x6b, 0x12, 0x39, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x62, 0x73,
	0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x68, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x64, 0x61, 0x74, 0x61, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x2e, 0x42, 0x75, 0x6c, 0x6b, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73,
	0x70, 0x65, 0x63, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x62, 0x73, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x68, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x64, 0x61, 0x74, 0x61, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2e, 0x42, 0x75, 0x6c, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x94, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x75, 0x6c, 0x6b,
	0x73, 0x52, 0x65, 0x75, 0x71, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x74, 0x66, 0x72, 0x6f,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x05, 0x74, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x2c, 0x0a, 0x03, 0x74, 0x74,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x03, 0x74, 0x74, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x63, 0x6c,
	0x75, 0x64, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x46, 0x0a, 0x0b, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x4f, 0x66, 0x42, 0x75, 0x6c, 0x6b, 0x12, 0x37, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x69, 0x6f, 0x2e, 0x63,
	0x6c, 0x62, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x68, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x64, 0x61,
	0x74, 0x61, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x22, 0x29, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x75, 0x6c, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x6c, 0x6b, 0x49, 0x64, 0x22, 0x2c,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x07,
	0x42, 0x75, 0x6c, 0x6b, 0x4a, 0x6f, 0x62, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x62,
	0x73, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x68, 0x65, 0x73, 0x2e, 0x70, 0x62, 0x74, 0x61, 0x73, 0x6b,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x90, 0x01, 0x0a, 0x0e, 0x42, 0x75, 0x6c,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x42,
	0x55, 0x4c, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x51, 0x55, 0x45, 0x55, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x42, 0x55, 0x4c, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15,
	0x42, 0x55, 0x4c, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50,
	0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x42, 0x55, 0x4c, 0x4b, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44,
	0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x42, 0x55, 0x4c, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x04, 0x42, 0x3d, 0x5a, 0x3b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x79, 0x62, 0x72, 0x6f, 0x73,
	0x6c, 0x61, 0x62, 0x73, 0x2f, 0x68, 0x65, 0x73, 0x2d, 0x32, 0x2d, 0x61, 0x70, 0x69, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x62, 0x64, 0x61, 0x74, 0x61, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
}

var file_pbdataproxy_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pbdataproxy_models_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pbdataproxy_models_proto_goTypes = []any{
	(BulkStatusCode)(0),                  // 0: io.clbs.openhes.pbdataproxy.BulkStatusCode
	(*CreateBulkRequest)(nil),            // 1: io.clbs.openhes.pbdataproxy.CreateBulkRequest
	(*BulkSpec)(nil),                     // 2: io.clbs.openhes.pbdataproxy.BulkSpec
	(*BulkStatus)(nil),                   // 3: io.clbs.openhes.pbdataproxy.BulkStatus
	(*BulkJobStatus)(nil),                // 4: io.clbs.openhes.pbdataproxy.BulkJobStatus
	(*Bulk)(nil),                         // 5: io.clbs.openhes.pbdataproxy.Bulk
	(*GetBulksReuqest)(nil),              // 6: io.clbs.openhes.pbdataproxy.GetBulksReuqest
	(*ArrayOfBulk)(nil),                  // 7: io.clbs.openhes.pbdataproxy.ArrayOfBulk
	(*GetBulkRequest)(nil),               // 8: io.clbs.openhes.pbdataproxy.GetBulkRequest
	(*GetJobStatusRequest)(nil),          // 9: io.clbs.openhes.pbdataproxy.GetJobStatusRequest
	(*BulkJob)(nil),                      // 10: io.clbs.openhes.pbdataproxy.BulkJob
	(*pbtaskmastermodels.JobDevice)(nil), // 11: io.clbs.openhes.pbtaskmaster.JobDevice
	(*pbdrivermodels.JobSettings)(nil),   // 12: io.clbs.openhes.pbdriver.JobSettings
	(*pbdrivermodels.JobAction)(nil),     // 13: io.clbs.openhes.pbdriver.JobAction
	(*pbtaskmastermodels.JobStatus)(nil), // 14: io.clbs.openhes.pbtaskmaster.JobStatus
	(*timestamppb.Timestamp)(nil),        // 15: google.protobuf.Timestamp
}
var file_pbdataproxy_models_proto_depIdxs = []int32{
	2,  // 0: io.clbs.openhes.pbdataproxy.CreateBulkRequest.spec:type_name -> io.clbs.openhes.pbdataproxy.BulkSpec
	11, // 1: io.clbs.openhes.pbdataproxy.BulkSpec.devices:type_name -> io.clbs.openhes.pbtaskmaster.JobDevice
	12, // 2: io.clbs.openhes.pbdataproxy.BulkSpec.settings:type_name -> io.clbs.openhes.pbdriver.JobSettings
	13, // 3: io.clbs.openhes.pbdataproxy.BulkSpec.job_actions:type_name -> io.clbs.openhes.pbdriver.JobAction
	0,  // 4: io.clbs.openhes.pbdataproxy.BulkStatus.status:type_name -> io.clbs.openhes.pbdataproxy.BulkStatusCode
	4,  // 5: io.clbs.openhes.pbdataproxy.BulkStatus.jobs:type_name -> io.clbs.openhes.pbdataproxy.BulkJobStatus
	14, // 6: io.clbs.openhes.pbdataproxy.BulkJobStatus.status:type_name -> io.clbs.openhes.pbtaskmaster.JobStatus
	2,  // 7: io.clbs.openhes.pbdataproxy.Bulk.spec:type_name -> io.clbs.openhes.pbdataproxy.BulkSpec
	3,  // 8: io.clbs.openhes.pbdataproxy.Bulk.status:type_name -> io.clbs.openhes.pbdataproxy.BulkStatus
	15, // 9: io.clbs.openhes.pbdataproxy.GetBulksReuqest.tfrom:type_name -> google.protobuf.Timestamp
	15, // 10: io.clbs.openhes.pbdataproxy.GetBulksReuqest.tto:type_name -> google.protobuf.Timestamp
	5,  // 11: io.clbs.openhes.pbdataproxy.ArrayOfBulk.items:type_name -> io.clbs.openhes.pbdataproxy.Bulk
	14, // 12: io.clbs.openhes.pbdataproxy.BulkJob.status:type_name -> io.clbs.openhes.pbtaskmaster.JobStatus
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pbdataproxy_models_proto_init() }
func file_pbdataproxy_models_proto_init() {
	if File_pbdataproxy_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbdataproxy_models_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbdataproxy_models_proto_goTypes,
		DependencyIndexes: file_pbdataproxy_models_proto_depIdxs,
		EnumInfos:         file_pbdataproxy_models_proto_enumTypes,
		MessageInfos:      file_pbdataproxy_models_proto_msgTypes,
	}.Build()
	File_pbdataproxy_models_proto = out.File
	file_pbdataproxy_models_proto_rawDesc = nil
	file_pbdataproxy_models_proto_goTypes = nil
	file_pbdataproxy_models_proto_depIdxs = nil
}
